// src/lib/screenMap.ts
/**
 * The app's real layout, in the words the model is given.
 *
 * Lifted out of the assistant's prompt so that two things can read the same text: the route that
 * answers questions, and the battery script that checks whether a cheaper model invents screens
 * that are not here. A copy would drift, and a drifted copy would make the battery pass while the
 * live prompt was wrong.
 *
 * Every line is a promise: if a place is not on this list, the model is told to say it is not sure
 * rather than guess a menu path.
 */

export const SCREEN_MAP = `WHERE THINGS LIVE ON SCREEN (the app's real layout — when telling a user where to click, use ONLY these; NEVER invent a menu path):
- Navigation is ONE BLACK BAR across the top (there is no sidebar): a direct Dashboard link, then three dropdown menus — Front Desk (WhatsApp /chats, Patients, Appointments, Leads), Operations (Finance, Inventory, Supply Store /store, Lab Tracking /lab, Time Clock /attendance), Insights & Growth (Intelligence /ai, Marketing, Reports) — plus the Settings gear, the notification bell and the account menu (Getting started /welcome, Help Center, language, Tour with Sara, Logout). On phones: a bottom bar (Dashboard, WhatsApp, Intelligence, Appointments, Finance, Patients) and a Menu button opening every page.
- Pages: Dashboard (/ — reception's desk view; a user whose role is Dentist sees their own home there instead: the next patient in their chair, their day, lab cases back for them, patients they left mid-treatment with no next visit, and their own money — what their patients paid today, their share if the clinic allows it, and what their patients still owe; an admin chooses between the desk, the owner's view (cash today, who's on the floor, the waiting room, then Money / Team / The floor / Growth tabs with every dentist by name) and — if also a dentist — the chair, under Settings → Interface → "Your home screen"), Patients (/patients — directory, each patient's file has tabs: Clinical, Treatment Plan, Finance, Overview, Timeline, X-rays, Prescriptions, Notes), Appointments (/appointments — the calendar; booking, statuses, the reception assistant panel), Finance (/finance — clinic-wide cash in/out, manual income & expense entries; /finance/recovery for unpaid balances), Inventory (/inventory), Reports (/reports — five reports with PDF/Excel export), Leads (/leads), Marketing (/marketing), Ortho (/ortho), Attendance (/attendance — the STAFF time clock), Help Center (/help), Intelligence (/ai — under Insights & Growth; ONE page with tabs: The Brief (today's/this week's numbers), Messages (the WhatsApp send queue — messages the system wrote, waiting for a person to press send), No-Shows (patients who did not turn up, and past appointments still needing an answer), The Bot (patient questions the WhatsApp assistant handed to a person). Deep links: /ai?tab=brief, /ai?tab=messages, /ai?tab=noshows, /ai?tab=bot. The old separate pages /ai/briefing, /messages and /ai/attendance now redirect into it), other AI pages (/ai/revenue, /ai/operations, /ai/reactivation), WhatsApp (/chats — the clinic's WhatsApp inbox; the assistant answers patients there), Lab Tracking (/lab — lab cases, due dates, remakes, what each lab is owed), Supply Store (/store — a partner supplier's shop, cash on delivery; only when connected), Getting started (/welcome — the setup checklist and Sara's tour of the whole system).
- Settings (/settings) is grouped into Personal, Clinic, People, and System & Automation, with a search box; each section has its own address (e.g. /settings/prices). The sections and their English/Arabic labels:
  Profile|الملف الشخصي · Attendance|الحضور · Schedule|الجدول (clinic hours, slot length, days off) · Branches & Rooms|الفروع والغرف · Recall|المتابعة · Prescriptions|الوصفات · Prices|الأسعار · Users|المستخدمين · Join Requests · Dentists|الأطباء (whether each dentist sees their share of what their patients paid, on their home screen) · Recently Deleted · Activity Logs · AI Credits · Alerts · WhatsApp · SMS · Theme · Interface · Online Booking · Patient Sources · Visit Reasons.
- THE PRICE LIST lives at Settings → Prices (الأسعار). That tab holds: the service catalog (every treatment with its price — add/edit/delete), price lists per branch with a blanket discount, discount reasons, and the discount ceiling for non-Admins. There is NO "Settings → Services" menu — the tab is named Prices.
- If a place is not in this list, say you are not sure where it is — offer navigate_to or a lesson instead of guessing.
`;
