/**
 * Every word the Excel backup writes, in both languages, in one place.
 *
 * Headers are bilingual (`Patients - المرضى`) because the file leaves the system: whoever opens
 * it — an accountant, a new owner, a lawyer — may read either language and has no app around to
 * switch. Kept as a table rather than spliced into the builder so the Arabic can be reviewed
 * without reading TypeScript, the same reasoning as settingsText.ts.
 *
 * Firebase-free and React-free on purpose: the builder that imports this runs in a route handler
 * and in a tsx test with no DOM.
 */

export const BACKUP_TEXT = {
  // --- Sheet names (no "/" — Excel forbids it in a sheet name) --------------------------------
  sheet_about: { en: "About", ar: "نبذة" },
  sheet_patients: { en: "Patients", ar: "المرضى" },
  sheet_appointments: { en: "Appointments", ar: "المواعيد" },
  sheet_ledger: { en: "Ledger", ar: "السجل المالي" },
  sheet_expenses: { en: "Expenses", ar: "المصروفات" },
  sheet_laborders: { en: "Lab orders", ar: "طلبات المعمل" },
  sheet_labpayments: { en: "Lab payments", ar: "مدفوعات المعامل" },
  sheet_labs: { en: "Labs", ar: "المعامل" },
  sheet_staff: { en: "Staff", ar: "الفريق" },
  sheet_prices: { en: "Prices", ar: "الأسعار" },
  sheet_attendance: { en: "Attendance", ar: "الحضور" },
  sheet_payroll: { en: "Payroll", ar: "الرواتب" },

  // --- About sheet -----------------------------------------------------------------------------
  about_clinic: { en: "Clinic", ar: "العيادة" },
  about_generated_at: { en: "Generated at", ar: "تاريخ الإنشاء" },
  about_generated_by: { en: "Generated by", ar: "أنشأها" },
  about_sheet_col: { en: "Sheet", ar: "الورقة" },
  about_rows_col: { en: "Rows", ar: "عدد الصفوف" },
  about_cash: {
    en: "Cash in / Cash out is money that actually moved: what was paid, or what was spent.",
    ar: "النقد الوارد / الصادر هو المال الذي تحرك فعلاً: ما تم دفعه أو ما تم صرفه.",
  },
  about_charged: {
    en: "Total charged is the price of the treatments recorded for the patient.",
    ar: "إجمالي المستحق هو سعر العلاجات المسجلة للمريض.",
  },
  about_balance: {
    en: "Balance owed = total charged - total paid. A negative balance means the patient has credit.",
    ar: "الرصيد المستحق = إجمالي المستحق - إجمالي المدفوع. الرصيد السالب يعني أن للمريض رصيداً دائناً.",
  },
  about_expenses_note: {
    en: "Expenses appear both on the Ledger sheet and on their own sheet.",
    ar: "المصروفات تظهر في ورقة السجل المالي وفي ورقتها الخاصة أيضاً.",
  },
  about_not_restore: {
    en: "This file is for reading and keeping. It cannot be imported back into the system.",
    ar: "هذا الملف للقراءة والحفظ. لا يمكن استيراده مرة أخرى إلى النظام.",
  },

  // --- Patients --------------------------------------------------------------------------------
  col_patients_file_no: { en: "File no.", ar: "رقم الملف" },
  col_patients_name: { en: "Name", ar: "الاسم" },
  col_patients_phone: { en: "Phone", ar: "الهاتف" },
  col_patients_gender: { en: "Gender", ar: "النوع" },
  col_patients_dob: { en: "Date of birth", ar: "تاريخ الميلاد" },
  col_patients_address: { en: "Address", ar: "العنوان" },
  col_patients_branch: { en: "Branch", ar: "الفرع" },
  col_patients_source: { en: "Source", ar: "المصدر" },
  col_patients_medical_history: { en: "Medical history", ar: "التاريخ المرضي" },
  col_patients_allergies: { en: "Allergies", ar: "الحساسية" },
  col_patients_status: { en: "Status", ar: "الحالة" },
  col_patients_registered_on: { en: "Registered on", ar: "تاريخ التسجيل" },
  col_patients_first_visit: { en: "First visit", ar: "أول زيارة" },
  col_patients_last_visit: { en: "Last visit", ar: "آخر زيارة" },
  col_patients_visits: { en: "Visits", ar: "عدد الزيارات" },
  col_patients_charged: { en: "Total charged", ar: "إجمالي المستحق" },
  col_patients_paid: { en: "Total paid", ar: "إجمالي المدفوع" },
  col_patients_owed: { en: "Balance owed", ar: "الرصيد المستحق" },
  col_patients_id: { en: "Patient ID", ar: "معرّف المريض" },

  // --- Appointments ----------------------------------------------------------------------------
  col_appointments_date: { en: "Date", ar: "التاريخ" },
  col_appointments_time: { en: "Time", ar: "الوقت" },
  col_appointments_patient: { en: "Patient", ar: "المريض" },
  col_appointments_phone: { en: "Phone", ar: "الهاتف" },
  col_appointments_dentist: { en: "Dentist", ar: "الطبيب" },
  col_appointments_treatment: { en: "Treatment", ar: "العلاج" },
  col_appointments_status: { en: "Status", ar: "الحالة" },
  col_appointments_duration: { en: "Duration (min)", ar: "المدة (دقيقة)" },
  col_appointments_branch: { en: "Branch", ar: "الفرع" },
  col_appointments_room: { en: "Room", ar: "الغرفة" },
  col_appointments_source: { en: "Source", ar: "المصدر" },
  col_appointments_cost: { en: "Cost", ar: "التكلفة" },
  col_appointments_notes: { en: "Notes", ar: "ملاحظات" },
  col_appointments_patient_id: { en: "Patient ID", ar: "معرّف المريض" },
  col_appointments_id: { en: "Appointment ID", ar: "معرّف الموعد" },

  // --- Ledger ----------------------------------------------------------------------------------
  col_ledger_date: { en: "Date", ar: "التاريخ" },
  col_ledger_type: { en: "Type", ar: "النوع" },
  col_ledger_patient: { en: "Patient", ar: "المريض" },
  col_ledger_dentist: { en: "Dentist", ar: "الطبيب" },
  col_ledger_description: { en: "Treatment / description", ar: "العلاج / الوصف" },
  col_ledger_category: { en: "Category", ar: "التصنيف" },
  col_ledger_method: { en: "Payment method", ar: "طريقة الدفع" },
  col_ledger_listed_amount: { en: "Listed amount", ar: "المبلغ المسجل" },
  col_ledger_discount: { en: "Discount", ar: "الخصم" },
  col_ledger_cash_in: { en: "Cash in", ar: "نقد وارد" },
  col_ledger_cash_out: { en: "Cash out", ar: "نقد صادر" },
  col_ledger_lab_fee: { en: "Lab fee", ar: "تكلفة المعمل" },
  col_ledger_commission: { en: "Dentist commission", ar: "نسبة الطبيب" },
  col_ledger_clinic_profit: { en: "Clinic profit", ar: "ربح العيادة" },
  col_ledger_payer: { en: "Payer", ar: "جهة الدفع" },
  col_ledger_status: { en: "Status", ar: "الحالة" },
  col_ledger_patient_id: { en: "Patient ID", ar: "معرّف المريض" },
  col_ledger_row_id: { en: "Row ID", ar: "معرّف الصف" },

  // --- Expenses --------------------------------------------------------------------------------
  col_expenses_date: { en: "Date", ar: "التاريخ" },
  col_expenses_description: { en: "Description", ar: "الوصف" },
  col_expenses_category: { en: "Category", ar: "التصنيف" },
  col_expenses_method: { en: "Payment method", ar: "طريقة الدفع" },
  col_expenses_amount: { en: "Amount", ar: "المبلغ" },
  col_expenses_notes: { en: "Notes", ar: "ملاحظات" },
  col_expenses_row_id: { en: "Row ID", ar: "معرّف الصف" },

  // --- Lab orders ------------------------------------------------------------------------------
  col_laborders_code: { en: "Code", ar: "الكود" },
  col_laborders_sent: { en: "Sent", ar: "تاريخ الإرسال" },
  col_laborders_due: { en: "Due", ar: "تاريخ الاستحقاق" },
  col_laborders_received: { en: "Received", ar: "تاريخ الاستلام" },
  col_laborders_fitted: { en: "Fitted", ar: "تاريخ التركيب" },
  col_laborders_patient: { en: "Patient", ar: "المريض" },
  col_laborders_dentist: { en: "Dentist", ar: "الطبيب" },
  col_laborders_lab: { en: "Lab", ar: "المعمل" },
  col_laborders_work_type: { en: "Work type", ar: "نوع العمل" },
  col_laborders_teeth: { en: "Teeth", ar: "الأسنان" },
  col_laborders_units: { en: "Units", ar: "الوحدات" },
  col_laborders_body_shade: { en: "Body shade", ar: "درجة اللون" },
  col_laborders_material: { en: "Material", ar: "الخامة" },
  col_laborders_agreed_price: { en: "Agreed price", ar: "السعر المتفق عليه" },
  col_laborders_status: { en: "Status", ar: "الحالة" },
  col_laborders_remake_of: { en: "Remake of", ar: "إعادة لطلب" },
  col_laborders_remake_reason: { en: "Remake reason", ar: "سبب الإعادة" },
  col_laborders_fault: { en: "Fault", ar: "المسؤول عن الخطأ" },
  col_laborders_id: { en: "Order ID", ar: "معرّف الطلب" },

  // --- Lab payments ----------------------------------------------------------------------------
  col_labpayments_date: { en: "Date", ar: "التاريخ" },
  col_labpayments_lab: { en: "Lab", ar: "المعمل" },
  col_labpayments_amount: { en: "Amount", ar: "المبلغ" },
  col_labpayments_method: { en: "Method", ar: "طريقة الدفع" },
  col_labpayments_reference: { en: "Reference", ar: "المرجع" },
  col_labpayments_note: { en: "Note", ar: "ملاحظة" },
  col_labpayments_id: { en: "Payment ID", ar: "معرّف الدفعة" },

  // --- Labs ------------------------------------------------------------------------------------
  col_labs_lab: { en: "Lab", ar: "المعمل" },
  col_labs_delivered_count: { en: "Cases delivered", ar: "الحالات المستلمة" },
  col_labs_delivered: { en: "Owed for delivered", ar: "المستحق عن المستلم" },
  col_labs_committed: { en: "Still at lab", ar: "ما زال في المعمل" },
  col_labs_paid: { en: "Paid", ar: "المدفوع" },
  col_labs_balance: { en: "Balance", ar: "الرصيد" },
  col_labs_remakes_lab_cost: { en: "Remakes at lab cost", ar: "إعادات على حساب المعمل" },

  // --- Staff -----------------------------------------------------------------------------------
  col_staff_name: { en: "Name", ar: "الاسم" },
  col_staff_role: { en: "Role", ar: "الدور" },
  col_staff_dentist: { en: "Dentist", ar: "طبيب" },
  col_staff_email: { en: "Email", ar: "البريد الإلكتروني" },
  col_staff_phone: { en: "Phone", ar: "الهاتف" },
  col_staff_active: { en: "Active", ar: "نشط" },
  col_staff_base_salary: { en: "Base salary", ar: "الراتب الأساسي" },
  col_staff_commission_pct: { en: "Commission %", ar: "نسبة العمولة %" },
  col_staff_overtime_multiplier: { en: "Overtime multiplier", ar: "معامل الوقت الإضافي" },
  col_staff_working_days: { en: "Working days", ar: "أيام العمل" },
  col_staff_id: { en: "Staff ID", ar: "معرّف الموظف" },

  // --- Prices ----------------------------------------------------------------------------------
  col_prices_service: { en: "Service", ar: "الخدمة" },
  col_prices_category: { en: "Category", ar: "التصنيف" },
  col_prices_pricing_mode: { en: "Pricing mode", ar: "طريقة التسعير" },
  col_prices_needs_lab: { en: "Needs lab", ar: "يحتاج معمل" },
  col_prices_est_lab_fee: { en: "Estimated lab fee", ar: "تكلفة المعمل التقديرية" },
  col_prices_base_price: { en: "Base price", ar: "السعر الأساسي" },
  inactive: { en: "inactive", ar: "غير نشطة" },

  // --- Attendance ------------------------------------------------------------------------------
  col_attendance_date: { en: "Date", ar: "التاريخ" },
  col_attendance_staff: { en: "Staff", ar: "الموظف" },
  col_attendance_check_in: { en: "Check in", ar: "الحضور" },
  col_attendance_check_out: { en: "Check out", ar: "الانصراف" },
  col_attendance_hours: { en: "Hours", ar: "الساعات" },
  col_attendance_status: { en: "Status", ar: "الحالة" },
  col_attendance_overtime_status: { en: "Overtime status", ar: "حالة الوقت الإضافي" },
  col_attendance_id: { en: "Punch ID", ar: "معرّف التسجيل" },

  // --- Payroll ---------------------------------------------------------------------------------
  col_payroll_month: { en: "Month", ar: "الشهر" },
  col_payroll_staff: { en: "Staff", ar: "الموظف" },
  col_payroll_role: { en: "Role", ar: "الدور" },
  col_payroll_scheduled_days: { en: "Scheduled days", ar: "أيام الجدول" },
  col_payroll_days_worked: { en: "Days worked", ar: "أيام العمل الفعلية" },
  col_payroll_hours: { en: "Hours worked", ar: "ساعات العمل" },
  col_payroll_late_days: { en: "Late days", ar: "أيام التأخير" },
  col_payroll_absent_days: { en: "Absent days", ar: "أيام الغياب" },
  col_payroll_overtime_approved: { en: "Overtime approved (h)", ar: "وقت إضافي معتمد (ساعة)" },
  col_payroll_overtime_pending: { en: "Overtime pending (h)", ar: "وقت إضافي قيد المراجعة (ساعة)" },
  col_payroll_estimated_pay: { en: "Estimated pay", ar: "الأجر التقديري" },

  // --- Enum values -----------------------------------------------------------------------------
  type_procedure: { en: "Treatment charge", ar: "رسوم علاج" },
  type_payment: { en: "Payment", ar: "دفعة" },
  type_income: { en: "Income", ar: "إيراد" },
  type_expense: { en: "Expense", ar: "مصروف" },
  fault_lab: { en: "The lab", ar: "المعمل" },
  fault_clinic: { en: "The clinic", ar: "العيادة" },
  fault_patient: { en: "The patient", ar: "المريض" },
  fault_unknown: { en: "Not sure", ar: "غير محدد" },
  mode_per_tooth: { en: "Per tooth", ar: "لكل سن" },
  mode_flat: { en: "Flat", ar: "سعر ثابت" },
  mode_per_arch: { en: "Per arch", ar: "لكل فك" },
  yes: { en: "Yes", ar: "نعم" },
  no: { en: "No", ar: "لا" },
} as const satisfies Record<string, { en: string; ar: string }>;

export type BackupTextKey = keyof typeof BACKUP_TEXT;

/** The separator between the two languages, everywhere. Never "/" — it is illegal in sheet names. */
export const BI_SEP = " - ";

/** `English - العربية` for one key. A missing key is a compile error, not a blank header. */
export function bi(key: BackupTextKey): string {
  const v = BACKUP_TEXT[key];
  return `${v.en}${BI_SEP}${v.ar}`;
}

/** The same shape for a label that comes from elsewhere (a stage label, a lab status). */
export function biRaw(en: string, ar: string): string {
  return en === ar ? en : `${en}${BI_SEP}${ar}`;
}
