import nextEnv from "@next/env";
(nextEnv as any).loadEnvConfig(process.cwd(), true, { info: () => {}, error: console.error });
const { adminDb } = await import("./src/lib/firebaseAdmin");
const admin = await import("firebase-admin");
adminDb();
const custom = await admin.default.auth().createCustomToken("mJO6e8TXc0VuBvGZWVPdg8WVtKG2");
const key = process.env.NEXT_PUBLIC_FIREBASE_API_KEY!;
const r = await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:signInWithCustomToken?key=${key}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: custom, returnSecureToken: true }) });
const { idToken } = (await r.json()) as any;
const res = await fetch("https://alpha-v3-live.vercel.app/api/automation/flush-lead-welcome", { headers: { Authorization: `Bearer ${idToken}` } });
console.log("flush:", res.status, (await res.text()).slice(0, 400));
