import { receiptElementToPdfBlob } from "@/lib/receiptPdfHtml";

export async function htmlToPdfBlob(srcDoc: string, rootId: string = "report-container"): Promise<Blob> {
  return new Promise((resolve, reject) => {
    const iframe = document.createElement("iframe");
    iframe.setAttribute("title", "html-to-pdf");
    iframe.setAttribute("aria-hidden", "true");

    // A4 width is 210mm. Give it physical width so layout works.
    iframe.style.cssText =
      "position:fixed;left:-10000px;top:0;width:210mm;height:297mm;border:0;opacity:0;pointer-events:none;z-index:-1;";

    document.body.appendChild(iframe);

    iframe.onload = async () => {
      try {
        const doc = iframe.contentDocument || iframe.contentWindow?.document;
        if (!doc) throw new Error("Iframe document not found");

        if (doc.fonts && doc.fonts.ready) {
          await doc.fonts.ready;
        }

        // Wait for rendering and shaping
        await new Promise((r) => setTimeout(r, 600));

        const root = doc.getElementById(rootId);
        if (!root) throw new Error(`Report PDF root '${rootId}' not found in iframe`);

        const blob = await receiptElementToPdfBlob(root);

        document.body.removeChild(iframe);
        resolve(blob);
      } catch (e) {
        document.body.removeChild(iframe);
        reject(e instanceof Error ? e : new Error("PDF generation failed"));
      }
    };

    iframe.onerror = () => {
      document.body.removeChild(iframe);
      reject(new Error("Failed to load iframe"));
    };

    iframe.srcdoc = srcDoc;
  });
}

const esc = (s: string) => (s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

export function buildReportHtmlBase(title: string, language: string, bodyContent: string): string {
  const isAr = language === "ar";
  const dir = isAr ? "rtl" : "ltr";
  
  return `
<!DOCTYPE html>
<html lang="${language}" dir="${dir}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>${esc(title)}</title>
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="anonymous" />
  <link href="https://fonts.googleapis.com/css2?family=Tajawal:wght@400;500;700;800;900&display=swap" rel="stylesheet" />
  <style>
    * { 
      font-family: 'Tajawal', Tahoma, system-ui, -apple-system, sans-serif !important; 
    }
    body { 
      margin: 0; 
      padding: 0; 
      background: #ffffff; 
      color: #0f172a;
      -webkit-print-color-adjust: exact !important; 
      print-color-adjust: exact !important; 
    }
    @page { 
      size: A4 portrait; 
      margin: 0; 
    }
  </style>
</head>
<body>
  <div id="report-container" style="box-sizing: border-box; max-width: 190mm; margin: 0 auto; padding: 10mm 15mm; overflow: hidden;">
    ${bodyContent}
    
    <div style="text-align: center; font-size: 11px; color: #94a3b8; margin-top: 40px; padding-top: 16px; border-top: 1px dashed #e2e8f0;">
      ${isAr ? "تم إنشاء التقرير بواسطة ألفا دينتال" : "Report generated by Alpha Dental"} &bull; ${new Date().toLocaleDateString("en-GB")}
    </div>
  </div>
</body>
</html>`;
}
