/**
 * Every bilingual label on the settings screens, in one place.
 *
 * They used to be spliced into the markup one at a time, hundreds of times, as
 * `language === "ar" ? "..." : "..."`. Nothing could be proofread, spell-checked or handed to
 * anyone to correct: finding every Arabic string meant reading every component. Here they sit
 * side by side, so a mistranslation is visible next to the English it is meant to match.
 *
 * Grouped by settings section. `tests/settingsRegistry.test.mts` checks that every entry has
 * both languages and that neither is blank — a missing Arabic string renders as nothing at
 * all, which reads as a broken screen rather than an untranslated one.
 */

export const SETTINGS_TEXT = {
  visitReasons: {
    title: { en: "Reasons for visit", ar: "أسباب الزيارة" },
    hint: { en: "The list reception picks from when booking an appointment.", ar: "القائمة التي يختار منها الاستقبال عند حجز موعد." },
    addPlaceholder: { en: "Add a reason...", ar: "أضف سبباً..." },
    add: { en: "Add reason", ar: "أضف سبباً" },
    empty: { en: "No reasons yet. Add the first one above.", ar: "لا توجد أسباب بعد. أضف الأول بالأعلى." },
    duplicate: { en: "That reason is already on the list.", ar: "هذا السبب موجود بالفعل." },
    saved: { en: "Reasons saved", ar: "تم حفظ الأسباب" },
    failed: { en: "Could not save. Try again.", ar: "تعذر الحفظ. حاول مرة أخرى." },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    remove: { en: "Remove", ar: "حذف" },
    countOne: { en: "reason", ar: "سبب" },
    countMany: { en: "reasons", ar: "أسباب" },
  },
  patientSources: {
    title: { en: "Patient sources", ar: "مصادر المرضى" },
    hint: { en: "How a patient found the clinic. Asked when their file is created, and what every marketing report counts.", ar: "كيف عرف المريض العيادة. يُسأل عند إنشاء ملفه، وعليه تُبنى تقارير التسويق." },
    addPlaceholder: { en: "Add a source...", ar: "أضف مصدراً..." },
    add: { en: "Add source", ar: "أضف مصدراً" },
    empty: { en: "No sources yet. Add the first one above.", ar: "لا توجد مصادر بعد. أضف الأول بالأعلى." },
    duplicate: { en: "That source is already on the list.", ar: "هذا المصدر موجود بالفعل." },
    saved: { en: "Sources saved", ar: "تم حفظ المصادر" },
    failed: { en: "Could not save. Try again.", ar: "تعذر الحفظ. حاول مرة أخرى." },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    remove: { en: "Remove", ar: "حذف" },
    countOne: { en: "source", ar: "مصدر" },
    countMany: { en: "sources", ar: "مصادر" },
  },
  aiCredits: {
    title: { en: "AI Credits", ar: "رصيد الذكاء الاصطناعي" },
    subtitle: { en: "Every AI action is logged here — who used what, for which patient, and what it cost.", ar: "كل استخدام للذكاء الاصطناعي بيتسجل هنا — مين استخدم إيه، ولمين، وكلّف كام." },
    used: { en: "Used", ar: "المستخدم" },
    limit: { en: "Monthly limit", ar: "الحد الشهري" },
    remaining: { en: "Remaining", ar: "المتبقي" },
    unlimited: { en: "Unlimited", ar: "غير محدود" },
    credits: { en: "credits", ar: "رصيد" },
    credit: { en: "credit", ar: "رصيد" },
    breakdown: { en: "Breakdown by feature", ar: "التوزيع حسب الخدمة" },
    unitemized: { en: "Not itemized (before logging started)", ar: "غير مفصّل (قبل تفعيل السجل)" },
    log: { en: "Usage log", ar: "سجل الاستخدام" },
    empty: { en: "No logged usage for this month yet", ar: "لا يوجد استخدام مسجل في هذا الشهر بعد" },
    when: { en: "When", ar: "الوقت" },
    feature: { en: "Feature", ar: "الخدمة" },
    patient: { en: "Patient", ar: "المريض" },
    byWho: { en: "By", ar: "بواسطة" },
    cost: { en: "Cost", ar: "التكلفة" },
    resetNote: { en: "Credits reset on the 1st of every month.", ar: "الرصيد بيتجدد أول كل شهر." },
  },
  alerts: {
    title: { en: "Alerts & Notifications", ar: "إعدادات التنبيهات" },
    subtitle: { en: "Manage precise routing for system alerts and messaging.", ar: "إدارة التوجيه الدقيق لتنبيهات النظام والمراسلات." },
    save: { en: "Save Alert Preferences", ar: "حفظ إعدادات التنبيهات" },
    inAppTitle: { en: "In-App Clinical Alerts", ar: "تنبيهات النظام الداخلي (In-App)" },
    inAppSub: { en: "Push notifications visible to doctors and front desk.", ar: "إشعارات تظهر للأطباء وموظفي الاستقبال." },
    eventPatientArrival: { en: "Patient Arrived (Waiting Area)", ar: "وصول المريض للعيادة" },
    eventLabReady: { en: "Lab Cases Received", ar: "استلام حالات المعمل" },
  },
  appearance: {
    langSettings: { en: "Language Settings", ar: "إعدادات اللغة" },
    switchLang: { en: "تغيير النظام إلى العربية", ar: "Switch System to English" },
    themeSettings: { en: "Clinic Appearance", ar: "مظهر العيادة" },
    themeHint: { en: "This applies to everyone in the clinic, on every device.", ar: "يظهر هذا المظهر لكل من يعمل في العيادة، على كل جهاز." },
    adminOnly: { en: "Only an owner or admin can change the appearance.", ar: "المدير أو المالك فقط يمكنه تغيير المظهر." },
    expired: { en: "This clinic's subscription has expired, so changes cannot be saved.", ar: "اشتراك العيادة منتهي — لا يمكن حفظ التغييرات." },
    suspended: { en: "This clinic is suspended, so changes cannot be saved.", ar: "العيادة موقوفة — لا يمكن حفظ التغييرات." },
    current: { en: "Current", ar: "الحالي" },
  },
  attendance: {
    attendanceTitle: { en: "Attendance Geofencing", ar: "نطاق الحضور الجغرافي" },
    attendanceSub: { en: "Restrict mobile clock-ins to this exact physical location.", ar: "تقييد تسجيل الدخول عبر الهاتف بهذا الموقع الفعلي." },
    autoGPS: { en: "Auto-Capture GPS", ar: "التقاط GPS تلقائياً" },
    lat: { en: "Latitude", ar: "خط العرض (Latitude)" },
    lng: { en: "Longitude", ar: "خط الطول (Longitude)" },
    radius: { en: "Allowed Radius (Meters)", ar: "النطاق المسموح (بالمتر)" },
    saveGeofence: { en: "Save Geofence", ar: "حفظ النطاق الجغرافي" },
  },
  clinicProfile: {
    back: { en: "Settings", ar: "الإعدادات" },
    title: { en: "Clinic profile", ar: "العيادة" },
    subtitle: { en: "Name, logo, contact details, Maps location, and a direct Google review link.", ar: "الاسم، الشعار، التواصل، رابط الخرائط، ورابط التقييم على جوجل." },
    name: { en: "Clinic name", ar: "اسم العيادة" },
    phone: { en: "Clinic phone", ar: "هاتف العيادة" },
    address: { en: "Address", ar: "العنوان" },
    maps: { en: "Google Maps URL (location)", ar: "رابط خرائط جوجل (الموقع)" },
    mapsHint: { en: "For directions to the clinic — not necessarily the write-a-review URL.", ar: "للمريض للوصول للعيادة — ليس بالضرورة رابط كتابة التقييم." },
    review: { en: "Google review link (direct)", ar: "رابط تقييم جوجل (مباشر)" },
    reviewHint: { en: "URL that opens Google’s review form for your clinic (Business Profile or short link). Used for WhatsApp {{google_link}}.", ar: "رابط يفتح صفحة ترك تقييم (مثلاً من ملف النشاط التجاري أو g.page). يُستخدم في واتساب {{google_link}}." },
    currency: { en: "Currency", ar: "العملة" },
    currencyHint: { en: "Shown beside every price, and on treatment plans and reports. For example EGP or SAR.", ar: "تظهر بجانب كل سعر وعلى خطط العلاج والتقارير. مثال: EGP أو SAR." },
    rxHeader: { en: "Prescription header", ar: "ترويسة الروشتة" },
    rxHeaderPlaceholder: { en: "Dr. Sarah Ahmed — Prosthodontist", ar: "د. أحمد محمود — أخصائي تجميل الأسنان" },
    rxHeaderHint: { en: "The line under the clinic name on every prescription. Leave it blank to print the treating dentist's name.", ar: "السطر أسفل اسم العيادة في كل روشتة. اتركه فارغاً ليظهر اسم الطبيب المعالج." },
    logo: { en: "Logo", ar: "الشعار" },
    logoHint: { en: "PNG or JPG — stored in Firebase Storage.", ar: "PNG أو JPG — يُرفع إلى التخزين السحابي." },
    save: { en: "Save", ar: "حفظ" },
    saved: { en: "Saved", ar: "تم الحفظ" },
    failed: { en: "Save failed", ar: "فشل الحفظ" },
    uploadFail: { en: "Upload failed", ar: "فشل رفع الصورة" },
    needAuth: { en: "Sign in required", ar: "سجّل الدخول" },
  },
  interface: {
    title: { en: "Interface Settings", ar: "واجهة الاستخدام" },
    followsYou: { en: "These choices are saved to your account, so they follow you to any device you sign in on — desktop, tablet or phone.", ar: "هذه الاختيارات محفوظة على حسابك، فتنتقل معك لأي جهاز تسجّل الدخول منه — الكمبيوتر، التابلت، أو الموبايل." },
    clinicalEditorLabel: { en: "Clinical Editor Mode", ar: "محرر الإجراءات السريرية" },
    inline: { en: "On the page", ar: "داخل الصفحة" },
    inlineHint: { en: "Chart on top, form beneath it, no overlay. Needs a wide screen.", ar: "المخطط فوق والنموذج تحته، من غير نافذة. يحتاج شاشة عريضة." },
    modalHint: { en: "A window over the page, with the teeth chart inside it.", ar: "نافذة فوق الصفحة، وبداخلها مخطط الأسنان." },
    drawerHint: { en: "A panel that slides in from the side.", ar: "لوح بينزلق من الجانب." },
    appointmentEditorLabel: { en: "Appointment Booking Mode", ar: "محرر المواعيد" },
    appointmentEditorDesc: { en: "Choose how you want to display the appointment booking and editing form.", ar: "اختر كيف تريد عرض نموذج حجز وتعديل المواعيد." },
    modal: { en: "Pop-up Modal", ar: "نافذة منبثقة" },
    drawer: { en: "Side Drawer", ar: "شريط جانبي" },
    panelModeLabel: { en: "Selected Appointment Panel", ar: "لوحة الموعد المحدد" },
    panelModeDesc: { en: "When you click an appointment, choose what appears beside the schedule: the edit form, or the AI reception assistant. You can flip between them at any time from a button at the top of the panel.", ar: "عند اختيار موعد، اختر ما يظهر بجانب الجدول: نموذج التعديل أم مساعد الاستقبال الذكي. يمكنك التبديل بينهما في أي وقت من زر أعلى اللوحة." },
    panelEditor: { en: "Details Editor", ar: "محرر التفاصيل" },
    panelEditorHint: { en: "The fields, ledger and payment button, exactly as now.", ar: "الحقول والسجل المالي وزر الدفع، كما هو." },
    panelAvatar: { en: "Reception Assistant", ar: "مساعد الاستقبال" },
    panelAvatarHint: { en: "Ask about the patient, or have it check in, reschedule, take a payment or message them — always on your confirmation.", ar: "اسأله عن المريض، أو اطلب منه الحضور والتغيير والدفع — بتأكيدك دائماً." },
  },
  prescriptions: {
    drugDbTitle: { en: "Drug Database", ar: "قاعدة بيانات الأدوية" },
    drugDbSub: { en: "Shortcuts for writing Prescriptions.", ar: "اختصارات لكتابة الوصفات الطبية." },
    addDrug: { en: "Add Drug", ar: "إضافة دواء" },
    noDrugs: { en: "No drugs saved yet.", ar: "لم يتم حفظ أي أدوية بعد." },
  },
  priceListWorkspace: {
    back: { en: "Back to lists", ar: "رجوع" },
    search: { en: "Search treatments...", ar: "ابحث عن علاج..." },
    all: { en: "All", ar: "الكل" },
    treatment: { en: "Treatment", ar: "العلاج" },
    standard: { en: "Standard", ar: "السعر الأساسي" },
    onThisList: { en: "On this list", ar: "على القائمة دي" },
    patientPays: { en: "Patient pays", ar: "المريض يدفع" },
    sameAsStandard: { en: "same as standard", ar: "زي الأساسي" },
    save: { en: "Save", ar: "حفظ" },
    noChanges: { en: "No changes yet", ar: "مفيش تغييرات" },
    discard: { en: "Discard", ar: "تراجع" },
    saved: { en: "Saved", ar: "اتحفظ" },
    failed: { en: "Could not save", ar: "فشل الحفظ" },
    none: { en: "No treatments found", ar: "مفيش علاجات" },
    bulkTitle: { en: "Quick fill", ar: "تسعير سريع" },
    bulkApply: { en: "Fill", ar: "املا" },
    bulkClear: { en: "Clear all", ar: "فضّي الكل" },
    leaveTitle: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفوظة" },
    leaveBody: { en: "Leaving now discards what you have typed. Leave anyway?", ar: "لو خرجت دلوقتي التغييرات هتضيع. تخرج؟" },
    leaveConfirm: { en: "Leave", ar: "اخرج" },
    standardWarning: { en: "Editing here changes the standard price itself, which every other list falls back to.", ar: "تعديل هنا بيغيّر السعر الأساسي نفسه، اللي كل القوائم التانية بترجع له." },
  },
  pricesPage: {
    title: { en: "Prices", ar: "الأسعار" },
    tab_treatments: { en: "Treatments", ar: "العلاجات" },
    tab_lists: { en: "Price lists", ar: "قوائم الأسعار" },
    tab_discounts: { en: "Discounts", ar: "الخصومات" },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    treatmentOne: { en: "treatment", ar: "علاج واحد" },
    treatmentTwo: { en: "treatments", ar: "علاجين" },
    treatmentFew: { en: "treatments", ar: "علاجات" },
    treatmentMany: { en: "treatments", ar: "علاج" },
    listOne: { en: "price list", ar: "قائمة أسعار واحدة" },
    listTwo: { en: "price lists", ar: "قائمتين أسعار" },
    listFew: { en: "price lists", ar: "قوائم أسعار" },
    listMany: { en: "price lists", ar: "قائمة أسعار" },
    ceilingUpTo: { en: "staff may discount up to", ar: "الموظف يخصم لغاية" },
    noCeiling: { en: "no ceiling on staff discounts", ar: "مفيش حد لخصم الموظفين" },
    rulesUnset: { en: "billing rules not set", ar: "علاج طريقة حسابه مش محددة" },
    rulesAllSet: { en: "All billing rules set", ar: "كل طرق الحساب محددة" },
  },
  priceLists: {
    title: { en: "Price lists", ar: "قوائم الأسعار" },
    subtitle: { en: "Different ways of charging for the same treatment. A list's blanket discount is prefilled on each line and stays visible.", ar: "طرق مختلفة لتسعير نفس العلاج — تأمين، عرض، سعر عائلة. الخصم العام بيتحط تلقائي وبيفضل ظاهر." },
    addList: { en: "New list", ar: "قائمة جديدة" },
    listName: { en: "List name", ar: "اسم القائمة" },
    blanket: { en: "Blanket discount", ar: "خصم عام" },
    makeDefault: { en: "Make default", ar: "اجعلها الافتراضية" },
    isDefault: { en: "Default", ar: "الافتراضية" },
    active: { en: "Active", ar: "شغالة" },
    inactive: { en: "Inactive", ar: "موقوفة" },
    deactivate: { en: "Deactivate", ar: "أوقف" },
    activate: { en: "Activate", ar: "شغّل" },
    remove: { en: "Delete", ar: "احذف" },
    cannotDeactivateDefault: { en: "The default list cannot be deactivated. Make another list the default first.", ar: "مينفعش توقف القائمة الافتراضية. خلي قائمة تانية افتراضية الأول." },
    inUse: { en: "Services are priced on this list, so it cannot be deleted. Deactivate it instead.", ar: "فيه خدمات مسعّرة على القائمة دي، فمينفعش تتحذف. أوقفها بدل الحذف." },
    confirmBlanketTitle: { en: "Change the blanket discount", ar: "تغيير الخصم العام" },
    confirmDeleteTitle: { en: "Delete price list", ar: "حذف القائمة" },
    reasonsTitle: { en: "Discount reasons", ar: "أسباب الخصم" },
    reasonsSub: { en: "A reason is required with every discount, so at month end you can see where the money went, not just that it went.", ar: "لازم سبب مع أي خصم — عشان آخر الشهر تعرف الفلوس راحت فين، مش بس إنها راحت." },
    addReason: { en: "New reason", ar: "سبب جديد" },
    capTitle: { en: "Discount ceiling for non-Admins", ar: "حد الخصم لغير المديرين" },
    capSub: { en: "The most anyone who is not an Admin can take off. Admins have no ceiling.", ar: "أعلى نسبة يقدر أي حد غير المدير يخصمها. المدير مالوش حد." },
    noCap: { en: "No ceiling", ar: "بدون حد" },
    saved: { en: "Saved", ar: "اتحفظ" },
    failed: { en: "Could not save", ar: "فشل الحفظ" },
    editPrices: { en: "Prices", ar: "الأسعار" },
    newListTitle: { en: "New price list", ar: "قائمة أسعار جديدة" },
    startFrom: { en: "Start from", ar: "تبدأ منين؟" },
    fresh: { en: "Start fresh", ar: "من الأول" },
    freshHint: { en: "Every treatment charges the standard price until you change it.", ar: "كل العلاجات هتتحاسب بالسعر الأساسي لحد ما تغيّرها." },
    copyHint: { en: "Copies that list's prices across, then you edit what differs.", ar: "بينسخ كل أسعار القائمة دي، وبعدين تعدّل اللي عايزه." },
    create: { en: "Create list", ar: "إنشاء" },
    listNamePlaceholder: { en: "e.g. Misr Insurance", ar: "مثلاً: تأمين مصر" },
    pricedNone: { en: "all at standard price", ar: "بالسعر الأساسي" },
    clinicWide: { en: "All branches", ar: "كل الفروع" },
    branchInherits: { en: "This branch charges the clinic-wide prices. Give it a list of its own if it charges differently.", ar: "الفرع ده بيحاسب بأسعار العيادة العامة. اعمل له قائمة لو أسعاره مختلفة." },
    orphaned: { en: "Lists on a deleted branch", ar: "فروع محذوفة" },
    branchLabel: { en: "Branch", ar: "الفرع" },
    branchAll: { en: "All branches (clinic-wide)", ar: "كل الفروع" },
    branchHint: { en: "The list is only offered at that branch. Leave it clinic-wide if every branch charges it.", ar: "القائمة دي هتظهر بس في الفرع ده. سيبها على كل الفروع لو الأسعار واحدة." },
  },
  pricing: {
    title: { en: "Services & Prices", ar: "الخدمات والأسعار" },
    subtitle: { en: "Each service has a category and an icon, shown everywhere services are picked.", ar: "كل خدمة لها فئة وأيقونة تظهران في كل مكان تُختار فيه." },
    searchTreatments: { en: "Search treatments...", ar: "البحث في العلاجات..." },
    addTreatment: { en: "Add treatment", ar: "إضافة علاج" },
    noTreatments: { en: "No treatments found", ar: "لم يتم العثور على علاجات" },
    all: { en: "All", ar: "الكل" },
    name: { en: "Treatment name", ar: "اسم العلاج" },
    price: { en: "Price", ar: "السعر" },
    category: { en: "Category", ar: "الفئة" },
    icon: { en: "Icon", ar: "الأيقونة" },
    suggested: { en: "suggested", ar: "مقترحة" },
    duration: { en: "Typical duration (minutes) — optional", ar: "المدة المعتادة (دقائق) — اختياري" },
    durationHint: { en: "Recorded for scheduling. Leave blank if it varies.", ar: "تُسجل للجدولة. اتركها فارغة إذا كانت تختلف." },
    billing: { en: "How the price is charged", ar: "طريقة حساب السعر" },
    ruleNotSet: { en: "Billing rule not set", ar: "طريقة الحساب لم تُحدد" },
    lab: { en: "Needs external lab work", ar: "يحتاج معمل خارجي" },
    labFee: { en: "Estimated lab fee", ar: "رسوم المعمل التقديرية" },
    newTreatment: { en: "New treatment", ar: "علاج جديد" },
    editTreatment: { en: "Edit treatment", ar: "تعديل العلاج" },
    save: { en: "Save", ar: "حفظ" },
    update: { en: "Update", ar: "تحديث" },
    minutes: { en: "min", ar: "د" },
  },
  recentlyDeleted: {
    title: { en: "Recently Deleted", ar: "المحذوفات مؤخراً" },
    sub: { en: "Deleted records are kept here until you restore them or remove them for good.", ar: "السجلات المحذوفة تُحفظ هنا حتى تستعيدها أو تحذفها نهائياً." },
    empty: { en: "Nothing has been deleted.", ar: "لا يوجد شيء محذوف." },
    noAccess: { en: "You have no delete permissions, so there is nothing here for you to see.", ar: "ليس لديك صلاحية حذف أي نوع من السجلات، فلا يوجد ما تراه هنا." },
    search: { en: "Search…", ar: "بحث..." },
    all: { en: "All types", ar: "كل الأنواع" },
    restore: { en: "Restore", ar: "استعادة" },
    purge: { en: "Delete permanently", ar: "حذف نهائي" },
    deletedBy: { en: "Deleted by", ar: "حذفها" },
    restored: { en: "Restored", ar: "تمت الاستعادة" },
    purged: { en: "Permanently deleted", ar: "تم الحذف نهائياً" },
    filesNote: { en: "Deleting a record is not erasure — image files are retained. For a true erasure request, use Delete permanently.", ar: "حذف السجل ليس محواً: ملفات الصور يُحتفظ بها. للمحو النهائي استخدم الحذف النهائي." },
    hasFiles: { en: "has files", ar: "يحتوي على ملفات" },
    purgeConfirm: { en: "This removes the record for good and it cannot be restored afterwards. Are you sure?", ar: "سيُحذف هذا السجل نهائياً ولا يمكن استعادته بعدها. متأكد؟" },
  },
  schedule: {
    scheduleTitle: { en: "Clinic Schedule", ar: "جدول العيادة" },
    scheduleSub: { en: "Set operating hours for the calendar.", ar: "تعيين ساعات العمل للتقويم." },
    openTime: { en: "Opening Time", ar: "وقت الفتح" },
    closeTime: { en: "Closing Time", ar: "وقت الإغلاق" },
    slotDuration: { en: "Slot Duration", ar: "مدة الموعد" },
    weekend: { en: "Days Off (Weekend)", ar: "أيام العطلة (نهاية الأسبوع)" },
    saveSchedule: { en: "Save Schedule", ar: "حفظ الجدول" },
  },
  shell: {
    title: { en: "Settings", ar: "الإعدادات" },
    subtitle: { en: "Everything you can configure, in one place.", ar: "كل ما يمكن ضبطه في العيادة، في مكان واحد." },
    search: { en: "Search settings", ar: "ابحث في الإعدادات" },
    noResults: { en: "No section by that name", ar: "لا يوجد قسم بهذا الاسم" },
    clear: { en: "Clear search", ar: "امسح البحث" },
    readOnly: { en: "This clinic's subscription has ended — you can look, but not save.", ar: "اشتراك العيادة منتهي — يمكنك الاطلاع دون حفظ." },
  },
  sms: {
    queueShowOlder: { en: "Show older messages", ar: "عرض رسائل أقدم" },
    queueLoadingOlder: { en: "Loading...", ar: "جارٍ التحميل..." },
    railOffBadge: { en: "Off", ar: "مطفأ" },
    railNoPhoneBadge: { en: "No phone", ar: "بلا هاتف" },
    railStalledBadge: { en: "Stalled", ar: "متوقف" },
    railLiveBadge: { en: "Sending", ar: "يعمل" },
    railOff: { en: "Text messages are switched off.", ar: "الرسائل النصية مطفأة." },
    railOffDetail: { en: "Nothing will be sent by SMS until you switch them on.", ar: "لن تُرسل أي رسالة نصية حتى تشغّلها." },
    railNoPhone: { en: "No phone is paired yet.", ar: "لا يوجد هاتف مربوط." },
    railNoPhoneDetail: { en: "Pair the clinic phone under Devices below and messages will start going out.", ar: "اربط هاتف العيادة من قسم الأجهزة بالأسفل لتبدأ الرسائل في الخروج." },
    railStalled: { en: "The phone has stopped checking in.", ar: "الهاتف توقف عن الاتصال." },
    railStalledDetail: { en: "Messages are queuing. Check the phone is on, online, and not asleep.", ar: "الرسائل تنتظر في الطابور. تأكد أن الهاتف شغال ومتصل بالإنترنت." },
    railLive: { en: "Sending from {phone}.", ar: "تُرسل من {phone}." },
    railLiveDetail: { en: "The phone is checking in and clearing the queue.", ar: "الهاتف متصل ويُفرّغ الطابور." },
    railWaiting: { en: "waiting", ar: "في الانتظار" },
    title: { en: "SMS from the clinic's phone", ar: "الرسائل النصية من هاتف العيادة" },
    costWarnTitle: { en: "Read this before turning it on", ar: "اقرأ هذا قبل التفعيل" },
    costWarn1: { en: "Every message is billed to the SIM. This is not free the way WhatsApp is.", ar: "كل رسالة تُحتسب على رصيد الشريحة. هذه الخاصية ليست مجانية مثل واتساب." },
    costWarn2: { en: "The phone must stay on, in signal, and the app must not be killed by battery saver.", ar: "يجب أن يظل الهاتف مفتوحاً، متصلاً بالشبكة، والتطبيق غير موقوف من إعدادات توفير البطارية." },
    costWarn3: { en: "A message containing a single Arabic character fits 70 characters instead of 160 — a long body means several billed messages.", ar: "الرسالة التي تحتوي على حرف عربي واحد تُحتسب ٧٠ حرفاً بدل ١٦٠ — النص الطويل يعني رسائل متعددة." },
    costWarn4: { en: "Carriers may restrict a consumer SIM that sends a lot of similar messages.", ar: "شركات المحمول قد تقيّد الشرائح العادية التي ترسل رسائل كثيرة متشابهة." },
    enable: { en: "Send from the clinic phone", ar: "تفعيل الإرسال من الهاتف" },
    optOutTitle: { en: "Opt-out line", ar: "سطر إيقاف الرسائل" },
    optOutToggle: { en: "Add \"reply to stop\" to the end of every text message", ar: "إضافة «للإيقاف أرسل إيقاف» في آخر كل رسالة نصية" },
    optOutHint: { en: "A patient who replies with the stop word is switched off for both SMS and WhatsApp together.", ar: "لما المريض يرد بكلمة «إيقاف» بتتوقف عنه رسائل الواتساب والنصية مع بعض." },
    optOutCost: { en: "Careful: the default bodies are written to fit one billed message (70 characters). This line pushes them into two — double the bill. Watch the segment counter below after you switch it on.", ar: "انتبه: القوالب الافتراضية مكتوبة لتدخل في رسالة واحدة (٧٠ حرفاً). السطر ده بيزوّدها لرسالتين — يعني ضعف الفاتورة. شوف عدّاد الرسائل تحت بعد ما تفعّله." },
    channelTitle: { en: "How the clinic's messages reach the patient", ar: "كيف تصل رسائل العيادة للمريض" },
    channelWhatsapp: { en: "WhatsApp only", ar: "واتساب فقط" },
    channelWhatsappHint: { en: "What happens today. No text messages are sent.", ar: "الوضع الحالي. لا تُرسل أي رسالة نصية." },
    channelSms: { en: "SMS only", ar: "رسالة نصية فقط" },
    channelSmsHint: { en: "Reaches every patient, including those with no WhatsApp.", ar: "لكل مريض، حتى من لا يستخدم واتساب." },
    channelBoth: { en: "Both", ar: "الاثنان معاً" },
    channelBothHint: { en: "The patient gets two messages about the same appointment, and you pay for the SMS.", ar: "المريض يستقبل رسالتين عن نفس الموعد، وتُحتسب تكلفة الرسالة النصية." },
    templateTitle: { en: "Which messages go out, and what they say", ar: "متى تُرسل الرسائل ونصها" },
    templateHint: { en: "Placeholders: {{patient_name}}, {{clinic_name}}, {{date}}, {{time}}, {{doctor}}. The payment message also has {{amount}} and {{balance}}.", ar: "المتغيرات المتاحة: {{patient_name}} و {{clinic_name}} و {{date}} و {{time}} و {{doctor}}. لرسالة الدفع أيضاً {{amount}} و {{balance}}." },
    resetTemplate: { en: "Reset to default", ar: "استعادة النص الافتراضي" },
    hourTitle: { en: "When the reminder goes out", ar: "ساعة إرسال التذكير" },
    hourHint: { en: "The system prepares tomorrow's reminders before dawn, and the phone holds them until the hour you pick. This applies to the reminder only — booking, change, cancellation and payment messages go out the moment they happen.", ar: "يجهّز النظام تذكيرات الغد فجراً، ويحتفظ بها الهاتف حتى الساعة التي تختارها. هذا يخصّ التذكير فقط — رسائل الحجز والتغيير والإلغاء والدفع تُرسل فور حدوثها." },
    hourLate: { en: "The phone checks the queue every 15 minutes, so a message may land a few minutes after the hour you picked.", ar: "الهاتف يفحص القائمة كل ١٥ دقيقة، لذلك قد تصل الرسالة بعد الساعة المختارة بدقائق." },
    eventOn: { en: "On", ar: "مفعّلة" },
    eventOff: { en: "Off", ar: "متوقفة" },
    allOff: { en: "No message is switched on — the phone has nothing to send.", ar: "لم تختر أي رسالة — لن يُرسل الهاتف شيئاً." },
    save: { en: "Save", ar: "حفظ" },
    saved: { en: "Saved", ar: "تم الحفظ" },
    segments: { en: "billed messages", ar: "رسالة مُحتسبة" },
    characters: { en: "characters", ar: "حرف" },
    devicesTitle: { en: "Sending phones", ar: "الهواتف المُرسِلة" },
    noDevices: { en: "No phone is sending. No text messages will go out until you turn the sender on, on the clinic phone.", ar: "لا يوجد هاتف يرسل حالياً. لن تُرسل أي رسالة نصية حتى تُفعّل الإرسال على هاتف العيادة." },
    pairButton: { en: "Pair a phone with a code", ar: "ربط هاتف بكود" },
    pairIntro: { en: "Type this code into the Alpha app on the clinic phone: More → Text messages → \"Pair with code\". Valid for 10 minutes, one use.", ar: "اكتب هذا الكود في تطبيق ألفا على هاتف العيادة: المزيد ← الرسائل النصية ← «ربط بالكود». صالح لمدة ١٠ دقائق ولمرة واحدة." },
    pairWaiting: { en: "Waiting for the phone…", ar: "في انتظار الهاتف…" },
    howToAdd: { en: "To add a phone: open the Alpha app on the clinic phone, go to More, and switch on \"Send reminders from this phone\". It appears here within a few minutes.", ar: "لإضافة هاتف: افتح تطبيق ألفا على هاتف العيادة، ثم «المزيد»، وفعّل «هذا الهاتف يرسل التذكيرات». سيظهر هنا خلال دقائق." },
    unpair: { en: "Stop", ar: "إيقاف" },
    unpairConfirm: { en: "Stop this phone from sending?", ar: "إيقاف هذا الهاتف عن الإرسال؟" },
    revoked: { en: "Stopped", ar: "موقوف" },
    aliveNow: { en: "Sending", ar: "يعمل الآن" },
    notSeen: { en: "Not checking in", ar: "غير متصل" },
    lastSeen: { en: "Last checked in", ar: "آخر اتصال" },
    instantOn: { en: "Instant", ar: "إرسال فوري" },
    instantOff: { en: "Every 15 min", ar: "كل ١٥ دقيقة" },
    instantOffHint: { en: "This phone needs app 4.8 or newer. After updating, wait for one check-in and sending becomes instant.", ar: "هذا الهاتف يحتاج تحديث التطبيق (٤.٨ أو أحدث). بعد التحديث انتظر فحصاً واحداً ليصبح الإرسال فورياً." },
    never: { en: "never", ar: "لم يحدث" },
    queueTitle: { en: "Recent messages", ar: "آخر الرسائل" },
    queueEmpty: { en: "Nothing in the queue yet.", ar: "لا توجد رسائل بعد." },
    statusQueued: { en: "Waiting", ar: "في الانتظار" },
    statusSending: { en: "With the phone", ar: "مع الهاتف" },
    statusSent: { en: "Sent", ar: "أُرسلت" },
    statusFailed: { en: "Failed", ar: "فشلت" },
    statusRetrying: { en: "Retrying", ar: "إعادة المحاولة" },
    queueNote: { en: "\"Waiting\" means the phone has not tried yet. \"Retrying\" means it tried, the network refused, and it will try again — the reason is written under the message. It only counts as sent once the phone confirms it.", ar: "«في الانتظار» تعني أن النظام جهّز الرسالة ولم يحاول الهاتف إرسالها بعد. «إعادة المحاولة» تعني أنه حاول ورفضتها الشبكة، وسيحاول مرة أخرى — والسبب مكتوب تحت الرسالة. لا تُعتبر مُرسلة إلا عندما يؤكد الهاتف ذلك." },
    inAppHint: { en: "You are viewing this inside the Alpha app on this phone, so you can pair it directly.", ar: "أنت تفتح النظام من داخل تطبيق ألفا على هذا الهاتف، لذلك يمكنك ربطه مباشرة." },
  },
  userAccess: {
    title: { en: "Manage Access", ar: "إدارة الصلاحيات" },
    systemRole: { en: "Primary System Role", ar: "دور النظام الأساسي" },
    alsoDentist: { en: "Also acts as Dentist (Shows in appointments)", ar: "يعمل أيضاً كطبيب (يظهر في المواعيد)" },
    adminBypass: { en: "The Admin role bypasses every switch below, so they're shown for reference only.", ar: "دور المدير (Admin) يتجاوز جميع هذه الصلاحيات تلقائياً، فهي معروضة للاطلاع فقط." },
    ownerBypass: { en: "The clinic owner bypasses every switch. No other admin can change their role, remove them, or reset their password.", ar: "مالك العيادة يتجاوز جميع الصلاحيات. مفيش مدير تاني يقدر يغيّر دوره أو يحذفه أو يغيّر كلمة مروره." },
    ownerLocked: { en: "Clinic owner", ar: "مالك العيادة" },
    ownerLockedHint: { en: "One owner per clinic. Use Transfer ownership to change who it is.", ar: "المالك واحد بس لكل عيادة. عشان تغيّره استخدم «نقل الملكية»." },
    searchPlaceholder: { en: "Search permissions...", ar: "بحث في الصلاحيات..." },
    selectAll: { en: "Select All", ar: "تحديد الكل" },
    deselectAll: { en: "Deselect All", ar: "إلغاء الكل" },
    presetMatches: { en: "matches the preset", ar: "مطابق للإعداد الجاهز" },
    presetUnset: { en: "not recorded yet — press Reset to preset", ar: "لسه متسجّلش — اضغط إعادة الضبط" },
    applyPreset: { en: "Reset to preset", ar: "إعادة الضبط" },
    applyPresetHint: { en: "Puts the switches back to what this role starts with, discarding hand-made changes.", ar: "يرجّع المفاتيح لما يبدأ به الدور ده، ويلغي أي تعديل يدوي." },
    transfer: { en: "Transfer clinic ownership", ar: "نقل ملكية العيادة" },
    transferHint: { en: "Makes this person the owner. You become an Admin.", ar: "يخلي الشخص ده مالك العيادة، وإنت تبقى مدير (Admin)." },
    always: { en: "Always", ar: "دائماً" },
  },
  userManagement: {
    noEmail: { en: "no email address on record", ar: "مفيش إيميل مسجل" },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    signedInPersonOne: { en: "person", ar: "شخص واحد" },
    signedInPersonTwo: { en: "people", ar: "شخصين" },
    signedInPersonFew: { en: "people", ar: "ناس" },
    signedInPersonMany: { en: "people", ar: "شخص" },
    brokenProfileOne: { en: "broken profile", ar: "ملف غير مكتمل" },
    brokenProfileTwo: { en: "broken profiles", ar: "ملفين مش مكتملين" },
    brokenProfileFew: { en: "broken profiles", ar: "ملفات مش مكتملة" },
    brokenProfileMany: { en: "broken profiles", ar: "ملف مش مكتمل" },
    title: { en: "User & Staff Management", ar: "إدارة المستخدمين والموظفين" },
    sub: { en: "Manage logins, roles, and granular permissions.", ar: "إدارة عمليات تسجيل الدخول والأدوار والصلاحيات." },
    addBtn: { en: "Add Team Member", ar: "إضافة عضو للفريق" },
    clinicIdTitle: { en: "Clinic ID", ar: "معرّف العيادة" },
    clinicIdHelp: { en: "Send this to a colleague who needs to join. They enter it on the \"Join an existing clinic\" screen after creating an account, and their request lands in the Join Requests tab.", ar: "ابعت المعرّف ده لأي زميل عايز ينضم للعيادة. هيحطه في شاشة «انضم لعيادة موجودة» بعد ما يعمل حساب، وهيوصلك طلبه في تبويب «طلبات الانضمام»." },
    clinicIdCopy: { en: "Copy", ar: "نسخ" },
    clinicIdCopied: { en: "Clinic ID copied", ar: "تم نسخ معرّف العيادة" },
    clinicIdCopyFailed: { en: "Couldn't copy — select the text and copy it manually", ar: "تعذّر النسخ — حدّد النص وانسخه يدوياً" },
    broken: { en: "Broken Profile", ar: "ملف غير مكتمل" },
    unnamed: { en: "Unnamed User", ar: "مستخدم بدون اسم" },
    unknown: { en: "Unknown", ar: "غير معروف" },
    deleteMsg: { en: "Permanently delete this user? They will be removed from all logins and schedules.", ar: "هل أنت متأكد من حذف هذا المستخدم نهائياً؟ سيتم إزالته من جميع جداول النظام." },
    accessControl: { en: "Permissions", ar: "صلاحيات الوصول" },
    authStatus: { en: "Auth Login:", ar: "تسجيل الدخول:" },
    staffStatus: { en: "Staff Profile:", ar: "ملف الموظف:" },
    active: { en: "Active", ar: "نشط" },
    missing: { en: "Missing! (Delete & Recreate)", ar: "مفقود! (احذف وأعد الإنشاء)" },
    successMsg: { en: "Permission updated", ar: "تم تحديث الصلاحيات" },
    errorMsg: { en: "Update failed", ar: "فشل التحديث" },
    resetBtnTitle: { en: "Direct Password Override", ar: "تغيير كلمة المرور" },
    searchPlaceholder: { en: "Search permissions...", ar: "بحث في الصلاحيات..." },
    permCount: { en: "enabled", ar: "مفعّل" },
    of: { en: "of", ar: "من" },
    sidebarNote: { en: "Sidebar: each item shows if you grant access.<page> or a legacy action key (e.g. patients.add). Settings icon: settings or access.settings.", ar: "القائمة: يظهر كل قسم إذا وُجد access.اسم_الصفحة أو أي مفتاح قديم مثل patients.add. الإعدادات: settings أو access.settings." },
    adminBypass: { en: "Admin role bypasses all permission checks.", ar: "المدير Admin يتجاوز كل القيود تلقائياً." },
    systemRole: { en: "System role", ar: "دور النظام" },
    alsoDentist: { en: "Also works as dentist (appointments & reports)", ar: "يعمل أيضاً كطبيب (يظهر في المواعيد والتقارير)" },
    roleUpdated: { en: "Role updated", ar: "تم تحديث الدور" },
    presetApplied: { en: "Reset to the role preset", ar: "تمت إعادة الضبط على الإعداد الجاهز" },
    transferred: { en: "Clinic ownership transferred", ar: "تم نقل ملكية العيادة" },
    dentistFlagUpdated: { en: "Dentist setting updated", ar: "تم تحديث إعداد الطبيب" },
  },
  users: {
    close: { en: "Close", ar: "إغلاق" },
    alsoDentist: { en: "Also works as dentist (shows in doctor lists & appointments)", ar: "يعمل أيضاً كطبيب (يظهر في قوائم الأطباء والمواعيد)" },
    title: { en: "Invite Team Member", ar: "إضافة عضو للفريق" },
    fullName: { en: "Full Name", ar: "الاسم الكامل" },
    email: { en: "Email Address", ar: "البريد الإلكتروني" },
    password: { en: "Initial Password", ar: "كلمة السر الأولية" },
    passwordHint: { en: "Minimum 6 characters", ar: "6 حروف على الأقل" },
    role: { en: "System Role", ar: "دور النظام" },
    roleDentist: { en: "Dentist", ar: "طبيب" },
    roleAssistant: { en: "Assistant", ar: "مساعد" },
    roleReceptionist: { en: "Receptionist", ar: "استقبال" },
    roleAdmin: { en: "Admin", ar: "مدير" },
    submit: { en: "Create System Login", ar: "إنشاء حساب الدخول" },
  },
} as const;

export type SettingsTextSection = keyof typeof SETTINGS_TEXT;

/** Resolve one section to the reader's language. */
export function settingsText<K extends SettingsTextSection>(
  section: K,
  language: string
): Record<keyof (typeof SETTINGS_TEXT)[K], string> {
  const ar = language === "ar";
  const source = SETTINGS_TEXT[section] as Record<string, { en: string; ar: string }>;
  const out: Record<string, string> = {};
  for (const key of Object.keys(source)) out[key] = ar ? source[key].ar : source[key].en;
  return out as Record<keyof (typeof SETTINGS_TEXT)[K], string>;
}
