/**
 * Every bilingual label on the settings screens, in one place.
 *
 * They used to be spliced into the markup one at a time, hundreds of times, as
 * `language === "ar" ? "..." : "..."`. Nothing could be proofread, spell-checked or handed to
 * anyone to correct: finding every Arabic string meant reading every component. Here they sit
 * side by side, so a mistranslation is visible next to the English it is meant to match.
 *
 * Grouped by settings section. `tests/settingsRegistry.test.mts` checks that every entry has
 * both languages and that neither is blank — a missing Arabic string renders as nothing at
 * all, which reads as a broken screen rather than an untranslated one.
 */

export const SETTINGS_TEXT = {
  visitReasons: {
    title: { en: "Reasons for visit", ar: "أسباب الزيارة" },
    hint: { en: "The list reception picks from when booking an appointment.", ar: "القائمة التي يختار منها الاستقبال عند حجز موعد." },
    addPlaceholder: { en: "Add a reason...", ar: "أضف سبباً..." },
    add: { en: "Add reason", ar: "أضف سبباً" },
    empty: { en: "No reasons yet. Add the first one above.", ar: "لا توجد أسباب بعد. أضف الأول بالأعلى." },
    duplicate: { en: "That reason is already on the list.", ar: "هذا السبب موجود بالفعل." },
    saved: { en: "Reasons saved", ar: "تم حفظ الأسباب" },
    failed: { en: "Could not save. Try again.", ar: "تعذر الحفظ. حاول مرة أخرى." },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    remove: { en: "Remove", ar: "حذف" },
    countOne: { en: "reason", ar: "سبب" },
    countMany: { en: "reasons", ar: "أسباب" },
  },
  patientSources: {
    title: { en: "Patient sources", ar: "مصادر المرضى" },
    hint: { en: "How a patient found the clinic. Asked when their file is created, and what every marketing report counts.", ar: "كيف عرف المريض العيادة. يُسأل عند إنشاء ملفه، وعليه تُبنى تقارير التسويق." },
    addPlaceholder: { en: "Add a source...", ar: "أضف مصدراً..." },
    add: { en: "Add source", ar: "أضف مصدراً" },
    empty: { en: "No sources yet. Add the first one above.", ar: "لا توجد مصادر بعد. أضف الأول بالأعلى." },
    duplicate: { en: "That source is already on the list.", ar: "هذا المصدر موجود بالفعل." },
    saved: { en: "Sources saved", ar: "تم حفظ المصادر" },
    failed: { en: "Could not save. Try again.", ar: "تعذر الحفظ. حاول مرة أخرى." },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    remove: { en: "Remove", ar: "حذف" },
    countOne: { en: "source", ar: "مصدر" },
    countMany: { en: "sources", ar: "مصادر" },
  },
  profile: {
    title: { en: "Your profile", ar: "ملفك الشخصي" },
    unnamed: { en: "Your name", ar: "اسمك" },
    staffId: { en: "Staff ID", ar: "رقم الموظف" },
    changePhoto: { en: "Change your photo", ar: "غيّر صورتك" },
    groupYou: { en: "You", ar: "بياناتك" },
    groupReach: { en: "How the clinic reaches you", ar: "طرق التواصل معاك" },
    groupClinic: { en: "Set by your clinic", ar: "العيادة هي اللي بتحددهم" },
    groupClinicHint: { en: "These two are not yours to change. Ask an admin if either is wrong.", ar: "الاتنين دول مش من حقك تغيّرهم. كلّم المدير لو فيه حاجة غلط." },
    name: { en: "Full name", ar: "الاسم بالكامل" },
    nickname: { en: "What people call you", ar: "الناس بتناديك بإيه" },
    nicknamePlaceholder: { en: "Shown on the schedule instead of your full name", ar: "بيظهر في الجدول بدل اسمك بالكامل" },
    bio: { en: "About you", ar: "نبذة عنك" },
    bioPlaceholder: { en: "Your specialty, the days you work, anything a colleague should know.", ar: "تخصصك، أيام شغلك، أي حاجة الزميل محتاج يعرفها." },
    phone: { en: "Phone number", ar: "رقم التليفون" },
    phoneInvalid: { en: "The phone number needs its country code first — for example +20 100 123 4567.", ar: "رقم التليفون لازم يبدأ بكود الدولة — مثلاً +20 100 123 4567." },
    email: { en: "Email address", ar: "البريد الإلكتروني" },
    role: { en: "Role", ar: "الدور" },
    imagesOnly: { en: "Images only", ar: "صور بس" },
    imageTooBig: { en: "The image must be under 5MB", ar: "الصورة لازم تكون أقل من 5 ميجا" },
    uploadFailed: { en: "Could not upload the photo", ar: "تعذر رفع الصورة" },
    photoUpdated: { en: "Photo updated", ar: "تم تحديث الصورة" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    saved: { en: "Profile updated", ar: "تم تحديث الملف الشخصي" },
    failed: { en: "Could not save your profile", ar: "تعذر حفظ الملف الشخصي" },
  },
  joinRequests: {
    title: { en: "Join Requests", ar: "طلبات الانضمام" },
    noneWaiting: { en: "Nobody is waiting to join.", ar: "مفيش حد مستني ينضم." },
    // The verb agrees with the count as well as the noun, so the clause is picked apart from
    // the counted noun rather than baked into it.
    waitingOne: { en: "is waiting to join this clinic.", ar: "مستني ينضم للعيادة." },
    waitingMany: { en: "are waiting to join this clinic.", ar: "مستنيين ينضموا للعيادة." },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    requestOne: { en: "person", ar: "شخص واحد" },
    requestTwo: { en: "people", ar: "شخصين" },
    requestFew: { en: "people", ar: "أشخاص" },
    requestMany: { en: "people", ar: "شخص" },
    howTheyArrive: { en: "Someone creates an account, enters your Clinic ID on the \"join an existing clinic\" screen, and lands here. The ID is on the Users page.", ar: "الشخص بيعمل حساب، بيدخل رقم العيادة في شاشة «انضم لعيادة موجودة»، وبيوصل هنا. الرقم موجود في صفحة المستخدمين." },
    emptyTitle: { en: "No pending requests", ar: "مفيش طلبات معلقة" },
    emptyHint: { en: "Anyone who asks to join this clinic appears here, with their name and email, for you to approve or turn down.", ar: "أي حد يطلب ينضم للعيادة هيظهر هنا باسمه وإيميله، عشان توافق أو ترفض." },
    unnamed: { en: "Unnamed", ar: "بدون اسم" },
    joinAs: { en: "as", ar: "كـ" },
    roleAdmin: { en: "Admin", ar: "مدير" },
    roleDentist: { en: "Dentist", ar: "طبيب" },
    roleReceptionist: { en: "Receptionist", ar: "استقبال" },
    roleAssistant: { en: "Assistant", ar: "مساعد" },
    approve: { en: "Approve", ar: "موافقة" },
    reject: { en: "Turn down", ar: "رفض" },
    approved: { en: "Approved — they can sign in now", ar: "تمت الموافقة — يقدر يدخل دلوقتي" },
    approveFailed: { en: "Could not approve", ar: "تعذرت الموافقة" },
    rejected: { en: "Request turned down", ar: "تم رفض الطلب" },
    rejectFailed: { en: "Could not turn the request down", ar: "تعذر رفض الطلب" },
    atLimit: { en: "Staff limit reached", ar: "وصلت للحد الأقصى" },
    limitToast: { en: "Your plan's staff limit is reached — upgrade before approving anyone else.", ar: "وصلت للحد الأقصى للموظفين في باقتك — لازم ترقّي قبل ما توافق على حد تاني." },
    limitNote: { en: "You have as many staff as your plan allows, so approving is switched off. Upgrade the plan, or remove someone from Users, and these become approvable again.", ar: "عندك عدد الموظفين اللي الباقة بتسمح بيه، فالموافقة مقفولة. رقّي الباقة، أو شيل حد من صفحة المستخدمين، والطلبات هترجع تتوافق." },
  },
  onlineBooking: {
    title: { en: "Online Booking", ar: "الحجز الإلكتروني" },
    onNote: { en: "Your booking page is live. Anyone with this link can request an appointment.", ar: "صفحة الحجز شغّالة. أي حد معاه اللينك ده يقدر يطلب موعد." },
    offNote: { en: "Your booking page is switched off — the link answers \"not found\" until you turn it back on.", ar: "صفحة الحجز مقفولة — اللينك بيرد بـ«غير موجود» لحد ما تشغّلها تاني." },
    on: { en: "Live", ar: "شغّالة" },
    off: { en: "Off", ar: "مقفولة" },
    enableLabel: { en: "Enable online booking", ar: "تفعيل الحجز الإلكتروني" },
    copy: { en: "Copy", ar: "نسخ" },
    copied: { en: "Link copied", ar: "تم نسخ الرابط" },
    copyFailed: { en: "Could not copy — select the link and copy it by hand.", ar: "تعذر النسخ — حدد الرابط وانسخه بإيدك." },
    taggedTitle: { en: "One link per channel", ar: "لينك لكل قناة" },
    taggedHint: { en: "Anyone who books through one of these is attributed to that channel automatically, with nobody typing anything — which is the whole of the source report.", ar: "أي حد يحجز من واحد من دول بيتسجل مصدره تلقائياً من غير ما حد يكتب حاجة — ده كل أساس تقرير المصادر." },
    chMeta: { en: "Facebook / Instagram ads", ar: "إعلانات فيسبوك/إنستجرام" },
    chInstagram: { en: "Instagram bio", ar: "البايو في إنستجرام" },
    chGoogle: { en: "Google / Maps profile", ar: "جوجل / الخرائط" },
    chTiktok: { en: "TikTok", ar: "تيك توك" },
    chWhatsapp: { en: "WhatsApp messages", ar: "رسايل واتساب" },
    heroTitle: { en: "Cover image", ar: "صورة الغلاف" },
    uploadHero: { en: "Upload a cover image", ar: "ارفع صورة غلاف" },
    changeHero: { en: "Change the cover image", ar: "غيّر صورة الغلاف" },
    uploading: { en: "Uploading…", ar: "جاري الرفع…" },
    imagesOnly: { en: "Images only", ar: "صور بس" },
    imageTooBig: { en: "The image must be under 5MB", ar: "الصورة لازم تكون أقل من 5 ميجا" },
    uploadFailed: { en: "Could not upload the image", ar: "تعذر رفع الصورة" },
    choicesTitle: { en: "What the patient chooses", ar: "المريض بيختار إيه" },
    doctorLabel: { en: "Let patients pick a doctor", ar: "المريض يختار الطبيب" },
    doctorHint: { en: "Off, and the clinic assigns whoever is free. On, and the patient's choice arrives with the request.", ar: "لو مقفولة، العيادة بتحدد المتاح. لو مفتوحة، اختيار المريض بيوصل مع الطلب." },
    durationLabel: { en: "How long an online booking reserves", ar: "الحجز الإلكتروني بيحجز قد إيه" },
    durationHint: { en: "The slot a request holds on the schedule until someone confirms it.", ar: "المساحة اللي الطلب بيحجزها في الجدول لحد ما حد يأكده." },
    minutes: { en: "minutes", ar: "دقيقة" },
    oneHour: { en: "1 hour", ar: "ساعة" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    saved: { en: "Booking settings saved", ar: "تم حفظ إعدادات الحجز" },
    failed: { en: "Save failed", ar: "فشل الحفظ" },
  },
  recall: {
    title: { en: "Recall & Reactivation", ar: "المتابعة وإعادة التفعيل" },
    notStated: { en: "Nobody has said how often patients should come back, so recall reminders stay switched off.", ar: "محدش حدد المريض يرجع كل قد إيه، فتذكيرات المتابعة مقفولة." },
    active: { en: "Active", ar: "شغّال" },
    notSet: { en: "Not set", ar: "مش متحدد" },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    monthOne: { en: "month", ar: "شهر واحد" },
    monthTwo: { en: "months", ar: "شهرين" },
    monthFew: { en: "months", ar: "شهور" },
    monthMany: { en: "months", ar: "شهر" },
    recallLabel: { en: "Due for a check-up after", ar: "الكشف الدوري بعد" },
    recallPlaceholder: { en: "e.g. 6", ar: "مثال: 6" },
    recallHint: { en: "Counted from the patient's last visit. After this long they appear on the recall list.", ar: "بتتحسب من آخر زيارة للمريض. بعد المدة دي بيظهر في قائمة المتابعة." },
    lapsedLabel: { en: "Counts as lapsed after", ar: "يتحسب منقطع بعد" },
    lapsedPlaceholder: { en: "e.g. 12", ar: "مثال: 12" },
    lapsedHint: { en: "Used by the reactivation scan to decide who is worth reaching out to again.", ar: "فحص إعادة التفعيل بيستخدمها عشان يحدد مين يستاهل نتواصل معاه تاني." },
    recallOff: { en: "Recall reminders are off until you state an interval. Nothing here assumes a number on your behalf — the feature would rather do nothing than present a guess as your clinic's policy.", ar: "تذكيرات المتابعة مقفولة لحد ما تحدد المدة. مفيش حاجة هنا بتفترض رقم بدالك — الميزة تفضل تقف بدل ما تقدّم تخمين على إنه سياسة عيادتك." },
    lapsedFallback: { en: "Until you set this, the reactivation scan uses {months} — a built-in default, not your clinic's decision. Its report says so when it runs.", ar: "لحد ما تحدد ده، فحص إعادة التفعيل بيستخدم {months} — رقم افتراضي جوه النظام، مش قرار عيادتك. التقرير بيقول كده وهو شغال." },
    recallInvalid: { en: "Enter a valid recall interval in months", ar: "اكتب عدد شهور صالح للمتابعة" },
    lapsedInvalid: { en: "Enter a valid lapsed threshold in months", ar: "اكتب عدد شهور صالح للانقطاع" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    saved: { en: "Saved", ar: "تم الحفظ" },
    failed: { en: "Save failed", ar: "فشل الحفظ" },
  },
  labs: {
    title: { en: "Dental Labs", ar: "المعامل" },
    railNote: { en: "The labs you send work to. They appear when raising a lab order, and each lab's usual turnaround fills the due date in for you.", ar: "المعامل اللي بتبعتلها شغل. بيظهروا وإنت بتعمل أمر معمل، ومدة التسليم بتاعت كل معمل بتملّي ميعاد الرجوع لوحدها." },
    nameIsKept: { en: "A case keeps the lab's name as it was when the case was raised, so renaming a lab here never rewrites old orders or paper already printed.", ar: "الحالة بتحتفظ باسم المعمل وقت ما اتعملت، فتغيير الاسم هنا مش بيغيّر الأوامر القديمة ولا الورق اللي اتطبع." },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    labOne: { en: "lab", ar: "معمل واحد" },
    labTwo: { en: "labs", ar: "معملين" },
    labFew: { en: "labs", ar: "معامل" },
    labMany: { en: "labs", ar: "معمل" },
    newLab: { en: "New lab name… (e.g. Cairo Dental Lab)", ar: "اسم المعمل الجديد… (مثال: معمل النور)" },
    addLab: { en: "Add lab", ar: "أضف معمل" },
    labExists: { en: "Lab already exists", ar: "المعمل موجود بالفعل" },
    deleteLab: { en: "Delete lab", ar: "حذف المعمل" },
    empty: { en: "No labs yet. Add at least one before raising a lab order.", ar: "مفيش معامل لسه. ضيف معمل واحد على الأقل عشان تقدر تعمل أمر معمل." },
    phone: { en: "Phone", ar: "التليفون" },
    whatsapp: { en: "WhatsApp (if different)", ar: "واتساب (لو مختلف)" },
    driver: { en: "Driver's name (optional)", ar: "اسم المندوب (اختياري)" },
    turnaround: { en: "Usual turnaround (days)", ar: "مدة التسليم بالأيام" },
    address: { en: "Address (optional)", ar: "العنوان (اختياري)" },
    withoutTurnaround: { en: "without a turnaround", ar: "من غير مدة تسليم" },
    noTurnaroundHint: { en: "Without a turnaround, the due date is typed by hand every time — and the overdue warnings stop meaning anything.", ar: "من غير مدة تسليم، ميعاد الرجوع هيتكتب بالإيد كل مرة — وتنبيهات التأخير مش هتبقى معناها حاجة." },
    priceList: { en: "Price list", ar: "أسعار المعمل" },
    nothingPriced: { en: "nothing priced yet", ar: "مفيش أسعار" },
    priceHint: { en: "Leave a box empty for work this lab does not do, or has no agreed price for. The price fills itself in when an order is raised, and can still be changed on any order.", ar: "سيب الخانة فاضية لو المعمل ده مبيعملش النوع ده، أو لسه مفيش سعر متفق عليه. السعر بيتحط لوحده في أمر المعمل، وتقدر تغيّره في أي أمر." },
    paperSize: { en: "Lab order paper size", ar: "مقاس ورق أمر المعمل" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    saved: { en: "Labs saved", ar: "تم حفظ المعامل" },
    failed: { en: "Save failed", ar: "فشل الحفظ" },
  },
  locations: {
    title: { en: "Branches & Rooms", ar: "الفروع والغرف" },
    railNote: { en: "Once you save, a branch and room picker appears on the booking form — and patients get a branch to choose from online, as soon as there is more than one.", ar: "أول ما تحفظ، هيظهر اختيار الفرع والغرفة في شاشة حجز المواعيد — والمريض هيختار الفرع من صفحة الحجز الأونلاين، أول ما يبقى فيه أكتر من فرع." },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    branchOne: { en: "branch", ar: "فرع واحد" },
    branchTwo: { en: "branches", ar: "فرعين" },
    branchFew: { en: "branches", ar: "فروع" },
    branchMany: { en: "branches", ar: "فرع" },
    roomOne: { en: "room", ar: "غرفة واحدة" },
    roomTwo: { en: "rooms", ar: "غرفتين" },
    roomFew: { en: "rooms", ar: "غرف" },
    roomMany: { en: "rooms", ar: "غرفة" },
    newBranch: { en: "New branch name… (e.g. Downtown Branch)", ar: "اسم الفرع الجديد… (مثال: فرع مدينة نصر)" },
    addBranch: { en: "Add branch", ar: "أضف فرع" },
    branchExists: { en: "Branch already exists", ar: "الفرع موجود بالفعل" },
    deleteBranch: { en: "Delete branch", ar: "حذف الفرع" },
    empty: { en: "No branches yet. If you work from a single location you can leave this empty — everything keeps working as it does now.", ar: "مفيش فروع لسه. لو عندك مكان واحد بس، ممكن تسيب الصفحة دي فاضية — كل حاجة هتشتغل عادي." },
    address: { en: "Address (optional)", ar: "العنوان (اختياري)" },
    phone: { en: "Phone (optional)", ar: "التليفون (اختياري)" },
    labCode: { en: "Lab code", ar: "كود المعمل" },
    labCodeHint: { en: "Lab orders from this branch will be numbered", ar: "أوامر المعمل من الفرع ده هتترقّم" },
    labCodeDerived: { en: "— derived from the name, change it if you like", ar: "(متولد من الاسم — غيّره لو حابب)" },
    sharedCode: { en: "Shared lab code", ar: "كود معمل متكرر" },
    sharedCodeHint: { en: "Another branch uses this code. They will share one counter, so no number is ever printed twice — but the code alone will not say which branch a case came from.", ar: "فرع تاني بنفس الكود. الفرعين هيتشاركوا نفس العداد، يعني الأرقام مش هتتكرر — بس الكود مش هيقولك الحالة جت منين." },
    rooms: { en: "Rooms / Chairs", ar: "الغرف / الكراسي" },
    newRoom: { en: "Room name… (e.g. Room 1)", ar: "اسم الغرفة… (مثال: غرفة 1)" },
    addRoom: { en: "Add room", ar: "أضف غرفة" },
    roomExists: { en: "Room already exists", ar: "الغرفة موجودة بالفعل" },
    deleteRoom: { en: "Remove room", ar: "حذف الغرفة" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    save: { en: "Save", ar: "حفظ" },
    discard: { en: "Discard", ar: "تجاهل" },
    saved: { en: "Branches saved", ar: "تم حفظ الفروع" },
    failed: { en: "Save failed", ar: "فشل الحفظ" },
  },
  aiCredits: {
    title: { en: "AI Credits", ar: "رصيد الذكاء الاصطناعي" },
    subtitle: { en: "Every AI action is logged here — who used what, for which patient, and what it cost.", ar: "كل استخدام للذكاء الاصطناعي بيتسجل هنا — مين استخدم إيه، ولمين، وكلّف كام." },
    used: { en: "Used", ar: "المستخدم" },
    limit: { en: "Monthly limit", ar: "الحد الشهري" },
    remaining: { en: "Remaining", ar: "المتبقي" },
    unlimited: { en: "Unlimited", ar: "غير محدود" },
    credits: { en: "credits", ar: "رصيد" },
    credit: { en: "credit", ar: "رصيد" },
    breakdown: { en: "Breakdown by feature", ar: "التوزيع حسب الخدمة" },
    unitemized: { en: "Not itemized (before logging started)", ar: "غير مفصّل (قبل تفعيل السجل)" },
    log: { en: "Usage log", ar: "سجل الاستخدام" },
    empty: { en: "No logged usage for this month yet", ar: "لا يوجد استخدام مسجل في هذا الشهر بعد" },
    when: { en: "When", ar: "الوقت" },
    feature: { en: "Feature", ar: "الخدمة" },
    patient: { en: "Patient", ar: "المريض" },
    byWho: { en: "By", ar: "بواسطة" },
    cost: { en: "Cost", ar: "التكلفة" },
    resetNote: { en: "Credits reset on the 1st of every month.", ar: "الرصيد بيتجدد أول كل شهر." },
    leftThisMonth: { en: "left this month", ar: "متبقي الشهر ده" },
    usedShort: { en: "used", ar: "مستخدم" },
    runningLow: { en: "Running low", ar: "الرصيد قرب يخلص" },
  },
  alerts: {
    title: { en: "Alerts & Notifications", ar: "إعدادات التنبيهات" },
    railNote: { en: "These appear inside the app, for doctors and the front desk. Nothing here sends an email or a message.", ar: "دي بتظهر جوه البرنامج للأطباء والاستقبال. مفيش حاجة هنا بتبعت إيميل ولا رسالة." },
    alertsOn: { en: "on", ar: "مفعّل" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    discard: { en: "Discard", ar: "تجاهل" },
    save: { en: "Save", ar: "حفظ" },
    inAppTitle: { en: "In-App Clinical Alerts", ar: "تنبيهات النظام الداخلي (In-App)" },
    inAppSub: { en: "Push notifications visible to doctors and front desk.", ar: "إشعارات تظهر للأطباء وموظفي الاستقبال." },
    eventPatientArrival: { en: "Patient Arrived (Waiting Area)", ar: "وصول المريض للعيادة" },
    eventLabReady: { en: "Lab Cases Received", ar: "استلام حالات المعمل" },
  },
  appearance: {
    langSettings: { en: "Language Settings", ar: "إعدادات اللغة" },
    switchLang: { en: "تغيير النظام إلى العربية", ar: "Switch System to English" },
    themeSettings: { en: "Clinic Appearance", ar: "مظهر العيادة" },
    adminOnly: { en: "Only an owner or admin can change the appearance.", ar: "المدير أو المالك فقط يمكنه تغيير المظهر." },
    expired: { en: "This clinic's subscription has expired, so changes cannot be saved.", ar: "اشتراك العيادة منتهي — لا يمكن حفظ التغييرات." },
    suspended: { en: "This clinic is suspended, so changes cannot be saved.", ar: "العيادة موقوفة — لا يمكن حفظ التغييرات." },
    current: { en: "Current", ar: "الحالي" },
    title: { en: "Theme", ar: "المظهر" },
    everyoneSees: { en: "Whatever you pick here is what everyone in the clinic sees, on every device. It is the clinic's look, not yours.", ar: "أي مظهر تختاره هنا هو اللي كل اللي في العيادة هيشوفه، على كل جهاز. ده مظهر العيادة، مش مظهرك إنت." },
    yoursIsInterface: { en: "The choices that are yours alone live under Interface.", ar: "الاختيارات اللي بتخصك إنت لوحدك موجودة في «واجهة الاستخدام»." },
    locked: { en: "Read only", ar: "للقراءة فقط" },
  },
  attendance: {
    attendanceTitle: { en: "Attendance Geofencing", ar: "نطاق الحضور الجغرافي" },
    attendanceSub: { en: "Restrict mobile clock-ins to this exact physical location.", ar: "تقييد تسجيل الدخول عبر الهاتف بهذا الموقع الفعلي." },
    autoGPS: { en: "Auto-Capture GPS", ar: "التقاط GPS تلقائياً" },
    lat: { en: "Latitude", ar: "خط العرض (Latitude)" },
    lng: { en: "Longitude", ar: "خط الطول (Longitude)" },
    radius: { en: "Allowed Radius (Meters)", ar: "النطاق المسموح (بالمتر)" },
    saveGeofence: { en: "Save Geofence", ar: "حفظ النطاق الجغرافي" },
  },
  clinicProfile: {
    title: { en: "Clinic profile", ar: "العيادة" },
    name: { en: "Clinic name", ar: "اسم العيادة" },
    phone: { en: "Clinic phone", ar: "هاتف العيادة" },
    address: { en: "Address", ar: "العنوان" },
    maps: { en: "Google Maps URL (location)", ar: "رابط خرائط جوجل (الموقع)" },
    mapsHint: { en: "For directions to the clinic — not necessarily the write-a-review URL.", ar: "للمريض للوصول للعيادة — ليس بالضرورة رابط كتابة التقييم." },
    review: { en: "Google review link (direct)", ar: "رابط تقييم جوجل (مباشر)" },
    reviewHint: { en: "URL that opens Google’s review form for your clinic (Business Profile or short link). Used for WhatsApp {{google_link}}.", ar: "رابط يفتح صفحة ترك تقييم (مثلاً من ملف النشاط التجاري أو g.page). يُستخدم في واتساب {{google_link}}." },
    currency: { en: "Currency", ar: "العملة" },
    currencyHint: { en: "Shown beside every price, and on treatment plans and reports. For example EGP or SAR.", ar: "تظهر بجانب كل سعر وعلى خطط العلاج والتقارير. مثال: EGP أو SAR." },
    rxHeader: { en: "Prescription header", ar: "ترويسة الروشتة" },
    rxHeaderPlaceholder: { en: "Dr. Sarah Ahmed — Prosthodontist", ar: "د. أحمد محمود — أخصائي تجميل الأسنان" },
    rxHeaderHint: { en: "The line under the clinic name on every prescription. Leave it blank to print the treating dentist's name.", ar: "السطر أسفل اسم العيادة في كل روشتة. اتركه فارغاً ليظهر اسم الطبيب المعالج." },
    logo: { en: "Logo", ar: "الشعار" },
    logoHint: { en: "PNG or JPG — stored in Firebase Storage.", ar: "PNG أو JPG — يُرفع إلى التخزين السحابي." },
    save: { en: "Save", ar: "حفظ" },
    saved: { en: "Saved", ar: "تم الحفظ" },
    failed: { en: "Save failed", ar: "فشل الحفظ" },
    uploadFail: { en: "Upload failed", ar: "فشل رفع الصورة" },
    needAuth: { en: "Sign in required", ar: "سجّل الدخول" },
    unnamed: { en: "Your clinic's name", ar: "اسم عيادتك" },
    railNote: { en: "This is the letterhead on every prescription and receipt, and the name your messages go out under.", ar: "دي الترويسة اللي بتتطبع على كل روشتة وإيصال، والاسم اللي رسايلك بتخرج بيه." },
    groupIdentity: { en: "Identity", ar: "الهوية" },
    groupContact: { en: "How patients reach you", ar: "طرق التواصل" },
    groupPrint: { en: "On printed documents", ar: "في المستندات المطبوعة" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    discard: { en: "Discard", ar: "تجاهل" },
  },
  interface: {
    title: { en: "Interface Settings", ar: "واجهة الاستخدام" },
    followsYou: { en: "These choices are saved to your account, so they follow you to any device you sign in on — desktop, tablet or phone.", ar: "هذه الاختيارات محفوظة على حسابك، فتنتقل معك لأي جهاز تسجّل الدخول منه — الكمبيوتر، التابلت، أو الموبايل." },
    clinicalEditorLabel: { en: "Clinical Editor Mode", ar: "محرر الإجراءات السريرية" },
    inline: { en: "On the page", ar: "داخل الصفحة" },
    inlineHint: { en: "Chart on top, form beneath it, no overlay. Needs a wide screen.", ar: "المخطط فوق والنموذج تحته، من غير نافذة. يحتاج شاشة عريضة." },
    modalHint: { en: "A window over the page, with the teeth chart inside it.", ar: "نافذة فوق الصفحة، وبداخلها مخطط الأسنان." },
    drawerHint: { en: "A panel that slides in from the side.", ar: "لوح بينزلق من الجانب." },
    appointmentEditorLabel: { en: "Appointment Booking Mode", ar: "محرر المواعيد" },
    appointmentEditorDesc: { en: "Choose how you want to display the appointment booking and editing form.", ar: "اختر كيف تريد عرض نموذج حجز وتعديل المواعيد." },
    modal: { en: "Pop-up Modal", ar: "نافذة منبثقة" },
    drawer: { en: "Side Drawer", ar: "شريط جانبي" },
    panelModeLabel: { en: "Selected Appointment Panel", ar: "لوحة الموعد المحدد" },
    panelModeDesc: { en: "When you click an appointment, choose what appears beside the schedule: the edit form, or the AI reception assistant. You can flip between them at any time from a button at the top of the panel.", ar: "عند اختيار موعد، اختر ما يظهر بجانب الجدول: نموذج التعديل أم مساعد الاستقبال الذكي. يمكنك التبديل بينهما في أي وقت من زر أعلى اللوحة." },
    panelEditor: { en: "Details Editor", ar: "محرر التفاصيل" },
    panelEditorHint: { en: "The fields, ledger and payment button, exactly as now.", ar: "الحقول والسجل المالي وزر الدفع، كما هو." },
    panelAvatar: { en: "Reception Assistant", ar: "مساعد الاستقبال" },
    panelAvatarHint: { en: "Ask about the patient, or have it check in, reschedule, take a payment or message them — always on your confirmation.", ar: "اسأله عن المريض، أو اطلب منه الحضور والتغيير والدفع — بتأكيدك دائماً." },

    savedInstantly: { en: "Saved as you choose", ar: "بيتحفظ أول ما تختار" },

    groupWhereOpens: { en: "Where things open", ar: "الحاجات بتفتح فين" },
    groupClinicalNote: { en: "The clinical note", ar: "الملف السريري" },
    groupAppointmentsPage: { en: "The appointments page", ar: "صفحة المواعيد" },

    clinicalEditorDesc: { en: "How the procedure editor opens. Your choice applies on every device — \"on the page\" needs a wide screen, and falls back to the pop-up on a phone.", ar: "شكل محرر الإجراءات. اختيارك بينطبق على كل الأجهزة — «داخل الصفحة» محتاج شاشة عريضة، وعلى الموبايل بيرجع للنافذة المنبثقة." },

    noteSortLabel: { en: "Order of procedures", ar: "ترتيب الإجراءات" },
    noteSortDesc: { en: "Which end of the treatment history a patient file opens on.", ar: "الملف بيفتح من أي ناحية في تاريخ العلاج." },
    sortNewest: { en: "Newest first", ar: "الأحدث أولاً" },
    sortNewestHint: { en: "The most recent procedure sits on top. The default.", ar: "آخر إجراء في الأعلى. ده الوضع الافتراضي." },
    sortOldest: { en: "Oldest first", ar: "الأقدم أولاً" },
    sortOldestHint: { en: "Reads as a treatment story from the beginning.", ar: "بيتقرا كقصة علاج من البداية." },
    sortManual: { en: "Manual", ar: "ترتيب يدوي" },
    sortManualHint: { en: "Arrange them yourself, by dragging or with the arrows.", ar: "ترتّبها بنفسك، بالسحب أو بالأسهم." },
    sortManualNote: { en: "Manual order is saved onto the patient file, so everyone who opens it sees the same arrangement — not just you. New procedures land at the end until you place them.", ar: "الترتيب اليدوي محفوظ على ملف المريض نفسه، فبيظهر لكل حد بيفتحه — مش ليك إنت بس. الإجراءات الجديدة بتيجي في آخر القائمة لحد ما ترتّبها." },

    noteGroupingLabel: { en: "Grouping", ar: "التجميع" },
    noteGroupingDesc: { en: "Whether procedures cluster by the visit they were done in.", ar: "الإجراءات تتجمّع حسب الزيارة اللي اتعملت فيها ولا لأ." },
    groupingFlat: { en: "One timeline", ar: "قائمة واحدة" },
    groupingFlatHint: { en: "Every procedure on a single continuous timeline.", ar: "كل الإجراءات في خط زمني واحد متصل." },
    groupingVisit: { en: "By visit", ar: "حسب الزيارة" },
    groupingVisitHint: { en: "Each visit in its own box, with its date and doctor.", ar: "كل زيارة في صندوق بتاريخها وطبيبها." },

    noteDensityLabel: { en: "Detail shown", ar: "حجم العرض" },
    noteDensityDesc: { en: "How much of each procedure the file shows before you open it.", ar: "الملف بيوري قد إيه من كل إجراء قبل ما تفتحه." },
    densityDetailed: { en: "Detailed", ar: "تفصيلي" },
    densityDetailedHint: { en: "The full card: status, tooth, doctor, notes and cost.", ar: "البطاقة كاملة: الحالة، السن، الطبيب، الملاحظات، والتكلفة." },
    densityCompact: { en: "Compact", ar: "مختصر" },
    densityCompactHint: { en: "One line per procedure — useful on long files.", ar: "سطر واحد لكل إجراء — مفيد في الملفات الطويلة." },

    visibilityLabel: { en: "Where the Appointments link shows", ar: "لينك المواعيد بيظهر فين" },
    visibilityDesc: { en: "Some clinics work the schedule only from the front desk, and want it out of the way on a phone.", ar: "فيه عيادات بتشتغل على الجدول من الاستقبال بس، وعايزة تشيله من على الموبايل." },
    visibilityAll: { en: "Everywhere", ar: "في كل مكان" },
    visibilityAllHint: { en: "In the menu on a phone and on a computer.", ar: "في القائمة على الموبايل وعلى الكمبيوتر." },
    visibilityDesktop: { en: "Computer only", ar: "الكمبيوتر بس" },
    visibilityDesktopHint: { en: "Hidden from the phone menu. The page still opens from a link.", ar: "مخفي من قائمة الموبايل. الصفحة لسه بتفتح من أي لينك." },
    visibilityHidden: { en: "Hidden", ar: "مخفي" },
    visibilityHiddenHint: { en: "Out of the menu on every device.", ar: "مش في القائمة على أي جهاز." },

    lateAlertLabel: { en: "Late patient alert", ar: "تنبيه المريض المتأخر" },
    lateAlertDesc: { en: "Show a flashing card when a patient is fifteen minutes late, with options for handling the delay.", ar: "يوري بطاقة وامضة لما المريض يتأخر ربع ساعة، ومعاها خيارات للتعامل مع التأخير." },
  },
  prescriptions: {
    drugDbTitle: { en: "Drug Database", ar: "قاعدة بيانات الأدوية" },
    drugDbSub: { en: "Shortcuts for writing Prescriptions.", ar: "اختصارات لكتابة الوصفات الطبية." },
    addDrug: { en: "Add Drug", ar: "إضافة دواء" },
    noDrugs: { en: "No drugs saved yet.", ar: "لم يتم حفظ أي أدوية بعد." },
  },
  priceListWorkspace: {
    back: { en: "Back to lists", ar: "رجوع" },
    search: { en: "Search treatments...", ar: "ابحث عن علاج..." },
    all: { en: "All", ar: "الكل" },
    treatment: { en: "Treatment", ar: "العلاج" },
    standard: { en: "Standard", ar: "السعر الأساسي" },
    onThisList: { en: "On this list", ar: "على القائمة دي" },
    patientPays: { en: "Patient pays", ar: "المريض يدفع" },
    sameAsStandard: { en: "same as standard", ar: "زي الأساسي" },
    save: { en: "Save", ar: "حفظ" },
    noChanges: { en: "No changes yet", ar: "مفيش تغييرات" },
    discard: { en: "Discard", ar: "تراجع" },
    saved: { en: "Saved", ar: "اتحفظ" },
    failed: { en: "Could not save", ar: "فشل الحفظ" },
    none: { en: "No treatments found", ar: "مفيش علاجات" },
    bulkTitle: { en: "Quick fill", ar: "تسعير سريع" },
    bulkApply: { en: "Fill", ar: "املا" },
    bulkClear: { en: "Clear all", ar: "فضّي الكل" },
    leaveTitle: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفوظة" },
    leaveBody: { en: "Leaving now discards what you have typed. Leave anyway?", ar: "لو خرجت دلوقتي التغييرات هتضيع. تخرج؟" },
    leaveConfirm: { en: "Leave", ar: "اخرج" },
    standardWarning: { en: "Editing here changes the standard price itself, which every other list falls back to.", ar: "تعديل هنا بيغيّر السعر الأساسي نفسه، اللي كل القوائم التانية بترجع له." },
  },
  pricesPage: {
    title: { en: "Prices", ar: "الأسعار" },
    tab_treatments: { en: "Treatments", ar: "العلاجات" },
    tab_lists: { en: "Price lists", ar: "قوائم الأسعار" },
    tab_discounts: { en: "Discounts", ar: "الخصومات" },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    treatmentOne: { en: "treatment", ar: "علاج واحد" },
    treatmentTwo: { en: "treatments", ar: "علاجين" },
    treatmentFew: { en: "treatments", ar: "علاجات" },
    treatmentMany: { en: "treatments", ar: "علاج" },
    listOne: { en: "price list", ar: "قائمة أسعار واحدة" },
    listTwo: { en: "price lists", ar: "قائمتين أسعار" },
    listFew: { en: "price lists", ar: "قوائم أسعار" },
    listMany: { en: "price lists", ar: "قائمة أسعار" },
    ceilingUpTo: { en: "staff may discount up to", ar: "الموظف يخصم لغاية" },
    noCeiling: { en: "no ceiling on staff discounts", ar: "مفيش حد لخصم الموظفين" },
    rulesUnset: { en: "billing rules not set", ar: "علاج طريقة حسابه مش محددة" },
    rulesAllSet: { en: "All billing rules set", ar: "كل طرق الحساب محددة" },
  },
  priceLists: {
    title: { en: "Price lists", ar: "قوائم الأسعار" },
    subtitle: { en: "Different ways of charging for the same treatment. A list's blanket discount is prefilled on each line and stays visible.", ar: "طرق مختلفة لتسعير نفس العلاج — تأمين، عرض، سعر عائلة. الخصم العام بيتحط تلقائي وبيفضل ظاهر." },
    addList: { en: "New list", ar: "قائمة جديدة" },
    listName: { en: "List name", ar: "اسم القائمة" },
    blanket: { en: "Blanket discount", ar: "خصم عام" },
    makeDefault: { en: "Make default", ar: "اجعلها الافتراضية" },
    isDefault: { en: "Default", ar: "الافتراضية" },
    active: { en: "Active", ar: "شغالة" },
    inactive: { en: "Inactive", ar: "موقوفة" },
    deactivate: { en: "Deactivate", ar: "أوقف" },
    activate: { en: "Activate", ar: "شغّل" },
    remove: { en: "Delete", ar: "احذف" },
    cannotDeactivateDefault: { en: "The default list cannot be deactivated. Make another list the default first.", ar: "مينفعش توقف القائمة الافتراضية. خلي قائمة تانية افتراضية الأول." },
    inUse: { en: "Services are priced on this list, so it cannot be deleted. Deactivate it instead.", ar: "فيه خدمات مسعّرة على القائمة دي، فمينفعش تتحذف. أوقفها بدل الحذف." },
    confirmBlanketTitle: { en: "Change the blanket discount", ar: "تغيير الخصم العام" },
    confirmDeleteTitle: { en: "Delete price list", ar: "حذف القائمة" },
    reasonsTitle: { en: "Discount reasons", ar: "أسباب الخصم" },
    reasonsSub: { en: "A reason is required with every discount, so at month end you can see where the money went, not just that it went.", ar: "لازم سبب مع أي خصم — عشان آخر الشهر تعرف الفلوس راحت فين، مش بس إنها راحت." },
    addReason: { en: "New reason", ar: "سبب جديد" },
    capTitle: { en: "Discount ceiling for non-Admins", ar: "حد الخصم لغير المديرين" },
    capSub: { en: "The most anyone who is not an Admin can take off. Admins have no ceiling.", ar: "أعلى نسبة يقدر أي حد غير المدير يخصمها. المدير مالوش حد." },
    noCap: { en: "No ceiling", ar: "بدون حد" },
    saved: { en: "Saved", ar: "اتحفظ" },
    failed: { en: "Could not save", ar: "فشل الحفظ" },
    editPrices: { en: "Prices", ar: "الأسعار" },
    newListTitle: { en: "New price list", ar: "قائمة أسعار جديدة" },
    startFrom: { en: "Start from", ar: "تبدأ منين؟" },
    fresh: { en: "Start fresh", ar: "من الأول" },
    freshHint: { en: "Every treatment charges the standard price until you change it.", ar: "كل العلاجات هتتحاسب بالسعر الأساسي لحد ما تغيّرها." },
    copyHint: { en: "Copies that list's prices across, then you edit what differs.", ar: "بينسخ كل أسعار القائمة دي، وبعدين تعدّل اللي عايزه." },
    create: { en: "Create list", ar: "إنشاء" },
    listNamePlaceholder: { en: "e.g. Misr Insurance", ar: "مثلاً: تأمين مصر" },
    pricedNone: { en: "all at standard price", ar: "بالسعر الأساسي" },
    clinicWide: { en: "All branches", ar: "كل الفروع" },
    branchInherits: { en: "This branch charges the clinic-wide prices. Give it a list of its own if it charges differently.", ar: "الفرع ده بيحاسب بأسعار العيادة العامة. اعمل له قائمة لو أسعاره مختلفة." },
    orphaned: { en: "Lists on a deleted branch", ar: "فروع محذوفة" },
    branchLabel: { en: "Branch", ar: "الفرع" },
    branchAll: { en: "All branches (clinic-wide)", ar: "كل الفروع" },
    branchHint: { en: "The list is only offered at that branch. Leave it clinic-wide if every branch charges it.", ar: "القائمة دي هتظهر بس في الفرع ده. سيبها على كل الفروع لو الأسعار واحدة." },
  },
  pricing: {
    title: { en: "Services & Prices", ar: "الخدمات والأسعار" },
    subtitle: { en: "Each service has a category and an icon, shown everywhere services are picked.", ar: "كل خدمة لها فئة وأيقونة تظهران في كل مكان تُختار فيه." },
    searchTreatments: { en: "Search treatments...", ar: "البحث في العلاجات..." },
    addTreatment: { en: "Add treatment", ar: "إضافة علاج" },
    noTreatments: { en: "No treatments found", ar: "لم يتم العثور على علاجات" },
    all: { en: "All", ar: "الكل" },
    name: { en: "Treatment name", ar: "اسم العلاج" },
    price: { en: "Price", ar: "السعر" },
    category: { en: "Category", ar: "الفئة" },
    icon: { en: "Icon", ar: "الأيقونة" },
    suggested: { en: "suggested", ar: "مقترحة" },
    duration: { en: "Typical duration (minutes) — optional", ar: "المدة المعتادة (دقائق) — اختياري" },
    durationHint: { en: "Recorded for scheduling. Leave blank if it varies.", ar: "تُسجل للجدولة. اتركها فارغة إذا كانت تختلف." },
    billing: { en: "How the price is charged", ar: "طريقة حساب السعر" },
    ruleNotSet: { en: "Billing rule not set", ar: "طريقة الحساب لم تُحدد" },
    lab: { en: "Needs external lab work", ar: "يحتاج معمل خارجي" },
    labFee: { en: "Estimated lab fee", ar: "رسوم المعمل التقديرية" },
    newTreatment: { en: "New treatment", ar: "علاج جديد" },
    editTreatment: { en: "Edit treatment", ar: "تعديل العلاج" },
    save: { en: "Save", ar: "حفظ" },
    update: { en: "Update", ar: "تحديث" },
    minutes: { en: "min", ar: "د" },
  },
  recentlyDeleted: {
    title: { en: "Recently Deleted", ar: "المحذوفات مؤخراً" },
    sub: { en: "Deleted records are kept here until you restore them or remove them for good.", ar: "السجلات المحذوفة تُحفظ هنا حتى تستعيدها أو تحذفها نهائياً." },
    empty: { en: "Nothing has been deleted.", ar: "لا يوجد شيء محذوف." },
    noAccess: { en: "You have no delete permissions, so there is nothing here for you to see.", ar: "ليس لديك صلاحية حذف أي نوع من السجلات، فلا يوجد ما تراه هنا." },
    search: { en: "Search…", ar: "بحث..." },
    all: { en: "All types", ar: "كل الأنواع" },
    restore: { en: "Restore", ar: "استعادة" },
    purge: { en: "Delete permanently", ar: "حذف نهائي" },
    deletedBy: { en: "Deleted by", ar: "حذفها" },
    keptUntil: { en: "Nothing leaves on its own — a record stays until you restore it or remove it for good.", ar: "مفيش حاجة بتمشي لوحدها — السجل بيفضل لحد ما تسترجعه أو تحذفه نهائي." },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts. Bare nouns —
    // countedNoun supplies the digit in English, and the sentence after them stands alone,
    // so there is no verb here to agree with the count.
    itemOne: { en: "deleted record", ar: "سجل واحد محذوف" },
    itemTwo: { en: "deleted records", ar: "سجلين محذوفين" },
    itemFew: { en: "deleted records", ar: "سجلات محذوفة" },
    itemMany: { en: "deleted records", ar: "سجل محذوف" },
    loadFailed: { en: "Could not load the bin", ar: "تعذر تحميل المحذوفات" },
    restoreFailed: { en: "Could not restore", ar: "تعذرت الاستعادة" },
    purgeFailed: { en: "Could not delete", ar: "تعذر الحذف" },
    restored: { en: "Restored", ar: "تمت الاستعادة" },
    purged: { en: "Permanently deleted", ar: "تم الحذف نهائياً" },
    filesNote: { en: "Deleting a record is not erasure — image files are retained. For a true erasure request, use Delete permanently.", ar: "حذف السجل ليس محواً: ملفات الصور يُحتفظ بها. للمحو النهائي استخدم الحذف النهائي." },
    hasFiles: { en: "has files", ar: "يحتوي على ملفات" },
    purgeConfirm: { en: "This removes the record for good and it cannot be restored afterwards. Are you sure?", ar: "سيُحذف هذا السجل نهائياً ولا يمكن استعادته بعدها. متأكد؟" },
  },
  schedule: {
    scheduleTitle: { en: "Clinic Schedule", ar: "جدول العيادة" },
    scheduleSub: { en: "Set operating hours for the calendar.", ar: "تعيين ساعات العمل للتقويم." },
    openTime: { en: "Opening Time", ar: "وقت الفتح" },
    closeTime: { en: "Closing Time", ar: "وقت الإغلاق" },
    slotDuration: { en: "Slot Duration", ar: "مدة الموعد" },
    hoursGroup: { en: "Opening hours", ar: "مواعيد العمل" },
    // "Weekend" was wrong: a clinic here may close on a Friday, a Friday and Saturday, or a
    // Tuesday because that is the day the dentist teaches. These are the days it is shut.
    closedGroup: { en: "Days the clinic is closed", ar: "الأيام اللي العيادة بتقفل فيها" },
    closedHint: { en: "Nothing can be booked on a closed day, and the online booking page skips it.", ar: "مفيش حجز بيتعمل في يوم مقفول، وصفحة الحجز الأونلاين بتعديه." },
    closedOnPrefix: { en: "closed", ar: "ومقفولة" },
    openEveryDay: { en: "open every day", ar: "ومفتوحة طول الأسبوع" },
    notSetYet: { en: "Opening hours are not set yet.", ar: "مواعيد العمل لسه مش متحددة." },
    minutes: { en: "minutes", ar: "دقيقة" },
    oneHour: { en: "1 hour", ar: "ساعة" },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    hourOne: { en: "hour open", ar: "ساعة واحدة شغل" },
    hourTwo: { en: "hours open", ar: "ساعتين شغل" },
    hourFew: { en: "hours open", ar: "ساعات شغل" },
    hourMany: { en: "hours open", ar: "ساعة شغل" },
    slotOne: { en: "appointment slot", ar: "موعد واحد" },
    slotTwo: { en: "appointment slots", ar: "موعدين" },
    slotFew: { en: "appointment slots", ar: "مواعيد" },
    slotMany: { en: "appointment slots", ar: "موعد" },
    daySunday: { en: "Sunday", ar: "الأحد" },
    dayMonday: { en: "Monday", ar: "الإثنين" },
    dayTuesday: { en: "Tuesday", ar: "الثلاثاء" },
    dayWednesday: { en: "Wednesday", ar: "الأربعاء" },
    dayThursday: { en: "Thursday", ar: "الخميس" },
    dayFriday: { en: "Friday", ar: "الجمعة" },
    daySaturday: { en: "Saturday", ar: "السبت" },
    unsaved: { en: "Unsaved changes", ar: "فيه تغييرات مش متحفظة" },
    discard: { en: "Discard", ar: "تجاهل" },
    saveSchedule: { en: "Save schedule", ar: "حفظ الجدول" },
  },
  shell: {
    title: { en: "Settings", ar: "الإعدادات" },
    search: { en: "Search settings", ar: "ابحث في الإعدادات" },
    noResults: { en: "No section by that name", ar: "لا يوجد قسم بهذا الاسم" },
    clear: { en: "Clear search", ar: "امسح البحث" },
    readOnly: { en: "This clinic's subscription has ended — you can look, but not save.", ar: "اشتراك العيادة منتهي — يمكنك الاطلاع دون حفظ." },
  },
  sms: {
    queueShowOlder: { en: "Show older messages", ar: "عرض رسائل أقدم" },
    queueLoadingOlder: { en: "Loading...", ar: "جارٍ التحميل..." },
    railOffBadge: { en: "Off", ar: "مطفأ" },
    railNoPhoneBadge: { en: "No phone", ar: "بلا هاتف" },
    railStalledBadge: { en: "Stalled", ar: "متوقف" },
    railLiveBadge: { en: "Sending", ar: "يعمل" },
    railOff: { en: "Text messages are switched off.", ar: "الرسائل النصية مطفأة." },
    railOffDetail: { en: "Nothing will be sent by SMS until you switch them on.", ar: "لن تُرسل أي رسالة نصية حتى تشغّلها." },
    railNoPhone: { en: "No phone is paired yet.", ar: "لا يوجد هاتف مربوط." },
    railNoPhoneDetail: { en: "Pair the clinic phone under Devices below and messages will start going out.", ar: "اربط هاتف العيادة من قسم الأجهزة بالأسفل لتبدأ الرسائل في الخروج." },
    railStalled: { en: "The phone has stopped checking in.", ar: "الهاتف توقف عن الاتصال." },
    railStalledDetail: { en: "Messages are queuing. Check the phone is on, online, and not asleep.", ar: "الرسائل تنتظر في الطابور. تأكد أن الهاتف شغال ومتصل بالإنترنت." },
    railLive: { en: "Sending from {phone}.", ar: "تُرسل من {phone}." },
    railLiveDetail: { en: "The phone is checking in and clearing the queue.", ar: "الهاتف متصل ويُفرّغ الطابور." },
    railWaiting: { en: "waiting", ar: "في الانتظار" },
    title: { en: "SMS from the clinic's phone", ar: "الرسائل النصية من هاتف العيادة" },
    costWarnTitle: { en: "Read this before turning it on", ar: "اقرأ هذا قبل التفعيل" },
    costWarn1: { en: "Every message is billed to the SIM. This is not free the way WhatsApp is.", ar: "كل رسالة تُحتسب على رصيد الشريحة. هذه الخاصية ليست مجانية مثل واتساب." },
    costWarn2: { en: "The phone must stay on, in signal, and the app must not be killed by battery saver.", ar: "يجب أن يظل الهاتف مفتوحاً، متصلاً بالشبكة، والتطبيق غير موقوف من إعدادات توفير البطارية." },
    costWarn3: { en: "A message containing a single Arabic character fits 70 characters instead of 160 — a long body means several billed messages.", ar: "الرسالة التي تحتوي على حرف عربي واحد تُحتسب ٧٠ حرفاً بدل ١٦٠ — النص الطويل يعني رسائل متعددة." },
    costWarn4: { en: "Carriers may restrict a consumer SIM that sends a lot of similar messages.", ar: "شركات المحمول قد تقيّد الشرائح العادية التي ترسل رسائل كثيرة متشابهة." },
    enable: { en: "Send from the clinic phone", ar: "تفعيل الإرسال من الهاتف" },
    optOutTitle: { en: "Opt-out line", ar: "سطر إيقاف الرسائل" },
    optOutToggle: { en: "Add \"reply to stop\" to the end of every text message", ar: "إضافة «للإيقاف أرسل إيقاف» في آخر كل رسالة نصية" },
    optOutHint: { en: "A patient who replies with the stop word is switched off for both SMS and WhatsApp together.", ar: "لما المريض يرد بكلمة «إيقاف» بتتوقف عنه رسائل الواتساب والنصية مع بعض." },
    optOutCost: { en: "Careful: the default bodies are written to fit one billed message (70 characters). This line pushes them into two — double the bill. Watch the segment counter below after you switch it on.", ar: "انتبه: القوالب الافتراضية مكتوبة لتدخل في رسالة واحدة (٧٠ حرفاً). السطر ده بيزوّدها لرسالتين — يعني ضعف الفاتورة. شوف عدّاد الرسائل تحت بعد ما تفعّله." },
    channelTitle: { en: "How the clinic's messages reach the patient", ar: "كيف تصل رسائل العيادة للمريض" },
    channelWhatsapp: { en: "WhatsApp only", ar: "واتساب فقط" },
    channelWhatsappHint: { en: "What happens today. No text messages are sent.", ar: "الوضع الحالي. لا تُرسل أي رسالة نصية." },
    channelSms: { en: "SMS only", ar: "رسالة نصية فقط" },
    channelSmsHint: { en: "Reaches every patient, including those with no WhatsApp.", ar: "لكل مريض، حتى من لا يستخدم واتساب." },
    channelBoth: { en: "Both", ar: "الاثنان معاً" },
    channelBothHint: { en: "The patient gets two messages about the same appointment, and you pay for the SMS.", ar: "المريض يستقبل رسالتين عن نفس الموعد، وتُحتسب تكلفة الرسالة النصية." },
    templateTitle: { en: "Which messages go out, and what they say", ar: "متى تُرسل الرسائل ونصها" },
    templateHint: { en: "Placeholders: {{patient_name}}, {{clinic_name}}, {{date}}, {{time}}, {{doctor}}. The payment message also has {{amount}} and {{balance}}.", ar: "المتغيرات المتاحة: {{patient_name}} و {{clinic_name}} و {{date}} و {{time}} و {{doctor}}. لرسالة الدفع أيضاً {{amount}} و {{balance}}." },
    resetTemplate: { en: "Reset to default", ar: "استعادة النص الافتراضي" },
    hourTitle: { en: "When the reminder goes out", ar: "ساعة إرسال التذكير" },
    hourHint: { en: "The system prepares tomorrow's reminders before dawn, and the phone holds them until the hour you pick. This applies to the reminder only — booking, change, cancellation and payment messages go out the moment they happen.", ar: "يجهّز النظام تذكيرات الغد فجراً، ويحتفظ بها الهاتف حتى الساعة التي تختارها. هذا يخصّ التذكير فقط — رسائل الحجز والتغيير والإلغاء والدفع تُرسل فور حدوثها." },
    hourLate: { en: "The phone checks the queue every 15 minutes, so a message may land a few minutes after the hour you picked.", ar: "الهاتف يفحص القائمة كل ١٥ دقيقة، لذلك قد تصل الرسالة بعد الساعة المختارة بدقائق." },
    eventOn: { en: "On", ar: "مفعّلة" },
    eventOff: { en: "Off", ar: "متوقفة" },
    allOff: { en: "No message is switched on — the phone has nothing to send.", ar: "لم تختر أي رسالة — لن يُرسل الهاتف شيئاً." },
    save: { en: "Save", ar: "حفظ" },
    saved: { en: "Saved", ar: "تم الحفظ" },
    segments: { en: "billed messages", ar: "رسالة مُحتسبة" },
    characters: { en: "characters", ar: "حرف" },
    devicesTitle: { en: "Sending phones", ar: "الهواتف المُرسِلة" },
    noDevices: { en: "No phone is sending. No text messages will go out until you turn the sender on, on the clinic phone.", ar: "لا يوجد هاتف يرسل حالياً. لن تُرسل أي رسالة نصية حتى تُفعّل الإرسال على هاتف العيادة." },
    pairButton: { en: "Pair a phone with a code", ar: "ربط هاتف بكود" },
    pairIntro: { en: "Type this code into the Alpha app on the clinic phone: More → Text messages → \"Pair with code\". Valid for 10 minutes, one use.", ar: "اكتب هذا الكود في تطبيق ألفا على هاتف العيادة: المزيد ← الرسائل النصية ← «ربط بالكود». صالح لمدة ١٠ دقائق ولمرة واحدة." },
    pairWaiting: { en: "Waiting for the phone…", ar: "في انتظار الهاتف…" },
    howToAdd: { en: "To add a phone: open the Alpha app on the clinic phone, go to More, and switch on \"Send reminders from this phone\". It appears here within a few minutes.", ar: "لإضافة هاتف: افتح تطبيق ألفا على هاتف العيادة، ثم «المزيد»، وفعّل «هذا الهاتف يرسل التذكيرات». سيظهر هنا خلال دقائق." },
    unpair: { en: "Stop", ar: "إيقاف" },
    unpairConfirm: { en: "Stop this phone from sending?", ar: "إيقاف هذا الهاتف عن الإرسال؟" },
    revoked: { en: "Stopped", ar: "موقوف" },
    aliveNow: { en: "Sending", ar: "يعمل الآن" },
    notSeen: { en: "Not checking in", ar: "غير متصل" },
    lastSeen: { en: "Last checked in", ar: "آخر اتصال" },
    instantOn: { en: "Instant", ar: "إرسال فوري" },
    instantOff: { en: "Every 15 min", ar: "كل ١٥ دقيقة" },
    instantOffHint: { en: "This phone needs app 4.8 or newer. After updating, wait for one check-in and sending becomes instant.", ar: "هذا الهاتف يحتاج تحديث التطبيق (٤.٨ أو أحدث). بعد التحديث انتظر فحصاً واحداً ليصبح الإرسال فورياً." },
    never: { en: "never", ar: "لم يحدث" },
    queueTitle: { en: "Recent messages", ar: "آخر الرسائل" },
    queueEmpty: { en: "Nothing in the queue yet.", ar: "لا توجد رسائل بعد." },
    statusQueued: { en: "Waiting", ar: "في الانتظار" },
    statusSending: { en: "With the phone", ar: "مع الهاتف" },
    statusSent: { en: "Sent", ar: "أُرسلت" },
    statusFailed: { en: "Failed", ar: "فشلت" },
    statusRetrying: { en: "Retrying", ar: "إعادة المحاولة" },
    queueNote: { en: "\"Waiting\" means the phone has not tried yet. \"Retrying\" means it tried, the network refused, and it will try again — the reason is written under the message. It only counts as sent once the phone confirms it.", ar: "«في الانتظار» تعني أن النظام جهّز الرسالة ولم يحاول الهاتف إرسالها بعد. «إعادة المحاولة» تعني أنه حاول ورفضتها الشبكة، وسيحاول مرة أخرى — والسبب مكتوب تحت الرسالة. لا تُعتبر مُرسلة إلا عندما يؤكد الهاتف ذلك." },
    inAppHint: { en: "You are viewing this inside the Alpha app on this phone, so you can pair it directly.", ar: "أنت تفتح النظام من داخل تطبيق ألفا على هذا الهاتف، لذلك يمكنك ربطه مباشرة." },
  },
  userAccess: {
    title: { en: "Manage Access", ar: "إدارة الصلاحيات" },
    systemRole: { en: "Primary System Role", ar: "دور النظام الأساسي" },
    alsoDentist: { en: "Also acts as Dentist (Shows in appointments)", ar: "يعمل أيضاً كطبيب (يظهر في المواعيد)" },
    adminBypass: { en: "The Admin role bypasses every switch below, so they're shown for reference only.", ar: "دور المدير (Admin) يتجاوز جميع هذه الصلاحيات تلقائياً، فهي معروضة للاطلاع فقط." },
    ownerBypass: { en: "The clinic owner bypasses every switch. No other admin can change their role, remove them, or reset their password.", ar: "مالك العيادة يتجاوز جميع الصلاحيات. مفيش مدير تاني يقدر يغيّر دوره أو يحذفه أو يغيّر كلمة مروره." },
    ownerLocked: { en: "Clinic owner", ar: "مالك العيادة" },
    ownerLockedHint: { en: "One owner per clinic. Use Transfer ownership to change who it is.", ar: "المالك واحد بس لكل عيادة. عشان تغيّره استخدم «نقل الملكية»." },
    searchPlaceholder: { en: "Search permissions...", ar: "بحث في الصلاحيات..." },
    selectAll: { en: "Select All", ar: "تحديد الكل" },
    deselectAll: { en: "Deselect All", ar: "إلغاء الكل" },
    presetMatches: { en: "matches the preset", ar: "مطابق للإعداد الجاهز" },
    presetUnset: { en: "not recorded yet — press Reset to preset", ar: "لسه متسجّلش — اضغط إعادة الضبط" },
    applyPreset: { en: "Reset to preset", ar: "إعادة الضبط" },
    applyPresetHint: { en: "Puts the switches back to what this role starts with, discarding hand-made changes.", ar: "يرجّع المفاتيح لما يبدأ به الدور ده، ويلغي أي تعديل يدوي." },
    transfer: { en: "Transfer clinic ownership", ar: "نقل ملكية العيادة" },
    transferHint: { en: "Makes this person the owner. You become an Admin.", ar: "يخلي الشخص ده مالك العيادة، وإنت تبقى مدير (Admin)." },
    always: { en: "Always", ar: "دائماً" },
  },
  userManagement: {
    noEmail: { en: "no email address on record", ar: "مفيش إيميل مسجل" },
    // Four shapes, because Arabic counts in four: see src/lib/arabicCount.ts.
    signedInPersonOne: { en: "person", ar: "شخص واحد" },
    signedInPersonTwo: { en: "people", ar: "شخصين" },
    signedInPersonFew: { en: "people", ar: "ناس" },
    signedInPersonMany: { en: "people", ar: "شخص" },
    brokenProfileOne: { en: "broken profile", ar: "ملف غير مكتمل" },
    brokenProfileTwo: { en: "broken profiles", ar: "ملفين مش مكتملين" },
    brokenProfileFew: { en: "broken profiles", ar: "ملفات مش مكتملة" },
    brokenProfileMany: { en: "broken profiles", ar: "ملف مش مكتمل" },
    title: { en: "User & Staff Management", ar: "إدارة المستخدمين والموظفين" },
    sub: { en: "Manage logins, roles, and granular permissions.", ar: "إدارة عمليات تسجيل الدخول والأدوار والصلاحيات." },
    addBtn: { en: "Add Team Member", ar: "إضافة عضو للفريق" },
    clinicIdTitle: { en: "Clinic ID", ar: "معرّف العيادة" },
    clinicIdHelp: { en: "Send this to a colleague who needs to join. They enter it on the \"Join an existing clinic\" screen after creating an account, and their request lands in the Join Requests tab.", ar: "ابعت المعرّف ده لأي زميل عايز ينضم للعيادة. هيحطه في شاشة «انضم لعيادة موجودة» بعد ما يعمل حساب، وهيوصلك طلبه في تبويب «طلبات الانضمام»." },
    clinicIdCopy: { en: "Copy", ar: "نسخ" },
    clinicIdCopied: { en: "Clinic ID copied", ar: "تم نسخ معرّف العيادة" },
    clinicIdCopyFailed: { en: "Couldn't copy — select the text and copy it manually", ar: "تعذّر النسخ — حدّد النص وانسخه يدوياً" },
    broken: { en: "Broken Profile", ar: "ملف غير مكتمل" },
    unnamed: { en: "Unnamed User", ar: "مستخدم بدون اسم" },
    unknown: { en: "Unknown", ar: "غير معروف" },
    deleteMsg: { en: "Permanently delete this user? They will be removed from all logins and schedules.", ar: "هل أنت متأكد من حذف هذا المستخدم نهائياً؟ سيتم إزالته من جميع جداول النظام." },
    accessControl: { en: "Permissions", ar: "صلاحيات الوصول" },
    authStatus: { en: "Auth Login:", ar: "تسجيل الدخول:" },
    staffStatus: { en: "Staff Profile:", ar: "ملف الموظف:" },
    active: { en: "Active", ar: "نشط" },
    missing: { en: "Missing! (Delete & Recreate)", ar: "مفقود! (احذف وأعد الإنشاء)" },
    successMsg: { en: "Permission updated", ar: "تم تحديث الصلاحيات" },
    errorMsg: { en: "Update failed", ar: "فشل التحديث" },
    resetBtnTitle: { en: "Direct Password Override", ar: "تغيير كلمة المرور" },
    searchPlaceholder: { en: "Search permissions...", ar: "بحث في الصلاحيات..." },
    permCount: { en: "enabled", ar: "مفعّل" },
    of: { en: "of", ar: "من" },
    sidebarNote: { en: "Sidebar: each item shows if you grant access.<page> or a legacy action key (e.g. patients.add). Settings icon: settings or access.settings.", ar: "القائمة: يظهر كل قسم إذا وُجد access.اسم_الصفحة أو أي مفتاح قديم مثل patients.add. الإعدادات: settings أو access.settings." },
    adminBypass: { en: "Admin role bypasses all permission checks.", ar: "المدير Admin يتجاوز كل القيود تلقائياً." },
    systemRole: { en: "System role", ar: "دور النظام" },
    alsoDentist: { en: "Also works as dentist (appointments & reports)", ar: "يعمل أيضاً كطبيب (يظهر في المواعيد والتقارير)" },
    roleUpdated: { en: "Role updated", ar: "تم تحديث الدور" },
    presetApplied: { en: "Reset to the role preset", ar: "تمت إعادة الضبط على الإعداد الجاهز" },
    transferred: { en: "Clinic ownership transferred", ar: "تم نقل ملكية العيادة" },
    dentistFlagUpdated: { en: "Dentist setting updated", ar: "تم تحديث إعداد الطبيب" },
  },
  users: {
    close: { en: "Close", ar: "إغلاق" },
    alsoDentist: { en: "Also works as dentist (shows in doctor lists & appointments)", ar: "يعمل أيضاً كطبيب (يظهر في قوائم الأطباء والمواعيد)" },
    title: { en: "Invite Team Member", ar: "إضافة عضو للفريق" },
    fullName: { en: "Full Name", ar: "الاسم الكامل" },
    email: { en: "Email Address", ar: "البريد الإلكتروني" },
    password: { en: "Initial Password", ar: "كلمة السر الأولية" },
    passwordHint: { en: "Minimum 6 characters", ar: "6 حروف على الأقل" },
    role: { en: "System Role", ar: "دور النظام" },
    roleDentist: { en: "Dentist", ar: "طبيب" },
    roleAssistant: { en: "Assistant", ar: "مساعد" },
    roleReceptionist: { en: "Receptionist", ar: "استقبال" },
    roleAdmin: { en: "Admin", ar: "مدير" },
    submit: { en: "Create System Login", ar: "إنشاء حساب الدخول" },
  },
} as const;

export type SettingsTextSection = keyof typeof SETTINGS_TEXT;

/** Resolve one section to the reader's language. */
export function settingsText<K extends SettingsTextSection>(
  section: K,
  language: string
): Record<keyof (typeof SETTINGS_TEXT)[K], string> {
  const ar = language === "ar";
  const source = SETTINGS_TEXT[section] as Record<string, { en: string; ar: string }>;
  const out: Record<string, string> = {};
  for (const key of Object.keys(source)) out[key] = ar ? source[key].ar : source[key].en;
  return out as Record<keyof (typeof SETTINGS_TEXT)[K], string>;
}
