/**
 * Every Arabic line the tour speaks, beside its English, as one page to read.
 *
 *   npx tsx scripts/tour-arabic-review.mts > tour-arabic.html
 *
 * The Arabic was written by a machine and has never been read end to end by someone who speaks
 * it. It is now the default voice on a tour that is meant to sound like a person, so it wants a
 * pass. Generated from the source rather than typed out, so it cannot fall behind, and grouped
 * the way the tour plays so a reviewer can follow the thread of it.
 */

import { TOUR_STOPS, TOUR_CHAPTERS, type TourStop } from "../src/lib/grandTour";

interface Line {
  where: string;
  en: string;
  ar: string;
}

const escape = (s: string) =>
  s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");

function linesOf(stop: TourStop): Line[] {
  const out: Line[] = [];
  const push = (where: string, l?: { en: string; ar: string } | null) => {
    if (l?.en && l?.ar) out.push({ where, en: l.en, ar: l.ar });
  };
  const walk = (where: string, actions: readonly unknown[] | undefined) => {
    for (const a of actions ?? []) {
      const action = a as Record<string, unknown>;
      push(where, action.say as { en: string; ar: string } | undefined);
      if (action.kind === "say") push(where, action.text as { en: string; ar: string });
      if (Array.isArray(action.then)) walk(where, action.then as unknown[]);
    }
  };
  push("title", stop.title);
  push("what she says", stop.say);
  for (const ask of stop.ask ?? []) push("suggested question", ask);
  walk("pointing", stop.walk);
  walk("doing", stop.demo);
  if (stop.handsOn) {
    push("your turn", stop.handsOn.say);
    push("when they finish", stop.handsOn.done);
    push("when they don't", stop.handsOn.gaveUp);
    push("when WhatsApp isn't connected", stop.handsOn.doneUnless?.say);
  }
  if (stop.phone) {
    push("on a phone", stop.phone.title);
    push("on a phone", stop.phone.say);
    walk("on a phone", stop.phone.walk);
  }
  return out;
}

const chapters = TOUR_CHAPTERS.map((c) => ({
  chapter: c,
  stops: TOUR_STOPS.filter((s) => s.chapter === c.id).map((s) => ({ stop: s, lines: linesOf(s) })),
})).filter((c) => c.stops.length > 0);

const total = chapters.reduce((a, c) => a + c.stops.reduce((b, s) => b + s.lines.length, 0), 0);

console.log(`<!-- generated by scripts/tour-arabic-review.mts -->
<title>Sara's Arabic</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&family=Plus+Jakarta+Sans:wght@400;500;700;800&display=swap">
<style>
  /* The app's own two faces and its one accent, so this reads as part of the product. */
  :root {
    --ground:#fbfaf8; --panel:#ffffff; --ink:#15171c; --soft:#6c7078; --hair:#e8e6e1;
    --accent:#a87b05; --accent-rule:#facc15; --slab:#15171c;
  }
  @media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
      --ground:#0c0d11; --panel:#15171c; --ink:#f4f4f5; --soft:#9096a0; --hair:#24272e;
      --accent:#facc15; --accent-rule:#facc15; --slab:#f4f4f5;
    }
  }
  :root[data-theme="dark"] {
    --ground:#0c0d11; --panel:#15171c; --ink:#f4f4f5; --soft:#9096a0; --hair:#24272e;
    --accent:#facc15; --accent-rule:#facc15; --slab:#f4f4f5;
  }
  * { box-sizing:border-box; }
  body { background:var(--ground); color:var(--ink); margin:0;
         font:400 15px/1.6 "Plus Jakarta Sans", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
  .wrap { max-width:64rem; margin:0 auto; padding:3rem 1.25rem 5rem; display:flex; flex-direction:column; gap:0; }
  header { display:flex; flex-direction:column; gap:.7rem; padding-bottom:1.75rem; border-bottom:2px solid var(--accent-rule); }
  h1 { font-size:clamp(1.8rem, 4vw, 2.4rem); font-weight:800; letter-spacing:-0.025em; margin:0; text-wrap:balance; }
  .lede { color:var(--soft); max-width:38rem; margin:0; font-size:.95rem; }
  .count { color:var(--soft); font-size:.8rem; font-variant-numeric:tabular-nums; margin:0; }
  h2 { font-size:.72rem; font-weight:800; text-transform:uppercase; letter-spacing:.16em; color:var(--accent);
       margin:2.75rem 0 .9rem; display:flex; align-items:baseline; gap:.6rem; }
  h2 .h2ar { font-family:"Cairo", "Segoe UI", Tahoma, sans-serif; letter-spacing:0; font-size:.95rem; color:var(--soft); direction:rtl; }
  .stop { background:var(--panel); border:1px solid var(--hair); border-radius:14px; padding:1.1rem 1.25rem 1.25rem; margin-bottom:.7rem; }
  .stop h3 { font-size:.98rem; font-weight:700; margin:0; letter-spacing:-0.01em; }
  .id { font:400 .7rem/1 ui-monospace, SFMono-Regular, Menlo, monospace; color:var(--soft); margin-top:.25rem; }
  .lines { display:flex; flex-direction:column; gap:0; margin-top:.9rem; }
  .line { display:grid; grid-template-columns:8.5rem minmax(0,1fr) minmax(0,1.15fr); gap:1rem;
          padding:.65rem 0; border-top:1px solid var(--hair); align-items:start; }
  .where { font-size:.66rem; font-weight:700; text-transform:uppercase; letter-spacing:.09em; color:var(--soft); padding-top:.22rem; }
  .en { color:var(--soft); font-size:.86rem; }
  /* The Arabic is what is under review, so it gets the weight and the size. */
  .ar { direction:rtl; text-align:right; font-family:"Cairo", "Segoe UI", Tahoma, sans-serif; font-size:1.05rem; line-height:1.75; }
  @media (max-width:52rem) {
    .line { grid-template-columns:1fr; gap:.3rem; }
    .where { padding-top:0; }
  }
</style>
<div class="wrap">
  <header>
    <h1>Sara's Arabic, all of it</h1>
    <p class="lede">Every line the tour speaks, in the order she says them: English for reference on the left,
    the Arabic under review on the right. It is Egyptian dialect, written by a machine, and now spoken aloud by
    default — so it wants a native ear. Mark anything that sounds translated rather than said.</p>
    <p class="count">${total} lines &middot; ${chapters.reduce((a, c) => a + c.stops.length, 0)} stops &middot; ${chapters.length} chapters</p>
  </header>`);

for (const { chapter, stops } of chapters) {
  console.log(`  <h2>${escape(chapter.title.en)}<span class="h2ar">${escape(chapter.title.ar)}</span></h2>`);
  for (const { stop, lines } of stops) {
    if (lines.length === 0) continue;
    console.log(`  <div class="stop"><h3>${escape(stop.title.en)}</h3><div class="id">${escape(stop.id)}</div><div class="lines">`);
    for (const line of lines) {
      console.log(
        `    <div class="line"><div class="where">${escape(line.where)}</div><div class="en">${escape(line.en)}</div><div class="ar">${escape(line.ar)}</div></div>`,
      );
    }
    console.log(`  </div></div>`);
  }
}
console.log(`</div>`);
